# DataFrame
- 2차원 배열
- 행과 열로 구성

In [2]:
import pandas as pd
# Dictionary를 이용한 DataFrame 생성
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}
dict_data

{'c0': [1, 2, 3],
 'c1': [4, 5, 6],
 'c2': [7, 8, 9],
 'c3': [10, 11, 12],
 'c4': [13, 14, 15]}

In [3]:
df = pd.DataFrame(dict_data)
df

   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [4]:
# List를 이용한 DataFrame 생성
df = pd.DataFrame(
    [[15, '남', '덕영중'],
    [17, '여', '수리중']],
    index = ['준서','예은'],
    columns=['나이','성별','학교']
    )
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [5]:
# 행과 열 이름 변경하기
print(df.index)
print(df.columns)

Index(['준서', '예은'], dtype='object')
Index(['나이', '성별', '학교'], dtype='object')

In [6]:
# 행 인덱스, 열 이름 변경하기 - 1
df.index = ['학생1', '학생2']
df.columns = ['연령','남녀','소속']
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [7]:
df = pd.DataFrame(
    [[15, '남', '덕영중'],
    [17, '여', '수리중']],
    index = ['준서','예은'],
    columns=['나이','성별','학교']
    )
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [8]:
df.rename(columns={'나이':'연령', '성별':'남녀', '학교':'소속'}, inplace=True) # 모든 컬럼에 적용**
df

    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [9]:
# 행 이름 변경하기
# df의 행 인덱스 중에서 '준서'를 '학생1'로, '예은'을 '학생2'로 바꾸기

df.rename(index={'준서':'학생1', '예은':'학생2' }, inplace=True)
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [10]:
df = pd.DataFrame(
                # 데이터
                [[90,98,85,100],
                [80,89,95,90],
                [70,95,100,90]],
                # 컬럼
                columns=['수학','영어','음악','체육'],
                # 행
                index=['서준','우현','인아']
                )
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [11]:
df = {'수학':[90,80,70], '영어':[98,89,95], '음악':[85,95,100], '체육':[100,90,90]}
df = pd.DataFrame(df, index=['서준','우현','인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

### 행삭제

In [12]:
df2 = df.copy()

In [13]:
df2

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [14]:
# df2의 index가 우현인 1개행을 삭제

df2.drop('우현', axis=0, inplace=True) # 결과 반영

In [15]:
df2

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [16]:
df3 = df.copy()

In [17]:
df3

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [18]:
# df3의 index가 우현과 인아인 2개 행을 삭제
df3.drop(['우현','인아'], axis=0, inplace=True)

In [19]:
# 열 삭제
df4 = df.copy()

In [20]:
df4

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [21]:
# df4의 수학 1개 열을 삭제
# axis='rows','column'
df4.drop('수학', axis=1, inplace=True)

In [22]:
df4

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [23]:
df5 = df.copy()

In [24]:
df5

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [25]:
df5.drop(['영어','음악'], axis=1, inplace=True)
df5

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [26]:
df5

    수학   체육
서준  90  100
우현  80   90
인아  70   90

### 행선택
- index 이름을 기준으로 선택할 경우에는 loc
- 정수형 위치 index를 사용할 경우에는 iloc

In [27]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [28]:
# index가 서준인 행을 선택
print(df.loc['서준'])
print(df.iloc[0])

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64
수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [35]:
# 행 인덱스를 사용하여 서준과 우현 2개의 행을 선택
# loc 사용
print(df.loc[['서준','우현']])

# iloc 사용
print(df.iloc[:2])

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90
    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

## 열 선택

In [36]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [37]:
df['수학']

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

In [38]:
df.수학

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

### 범위 Slicing 활용
- dataFrame.iloc[시작index:끝인덱스:증가치]

In [39]:
df.iloc[::2] # 처음부터 끝까지 2씩 증가시킴

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [40]:
df.iloc[0:3:2]

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [41]:
# 인덱스 역순으로 출력
df.iloc[::-1]

    수학  영어   음악   체육
인아  70  95  100   90
우현  80  89   95   90
서준  90  98   85  100

# 행과 열을 이용한 데이터 선택

In [63]:
exam_data = {'수학':[90,80,70], '영어':[98,89,95],
 '음악':[85,95,100], '체육':[100,90,90], '이름': ['서준','우현','인아'] }
df = pd.DataFrame(exam_data)
df

   수학  영어   음악   체육  이름
0  90  98   85  100  서준
1  80  89   95   90  우현
2  70  95  100   90  인아

In [64]:
df.set_index('이름', inplace=True)
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [65]:
print(df.loc['서준',['음악','체육']])
print(df.iloc[0,2:4])
print(df.loc['서준','음악':'체육'])
print(df.loc['서준','음악':])

음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64

In [66]:
df['국어'] = 80
df

    수학  영어   음악   체육  국어
이름
서준  90  98   85  100  80
우현  80  89   95   90  80
인아  70  95  100   90  80

In [67]:
df.loc['철수'] = [10, 20, 30, 40, 50]
df

    수학  영어   음악   체육  국어
이름
서준  90  98   85  100  80
우현  80  89   95   90  80
인아  70  95  100   90  80
철수  10  20   30   40  50

In [68]:
df.loc['영희'] = df.loc['인아']
df

    수학  영어   음악   체육  국어
이름
서준  90  98   85  100  80
우현  80  89   95   90  80
인아  70  95  100   90  80
철수  10  20   30   40  50
영희  70  95  100   90  80

In [69]:
# 서준의 체육점수를 80점으로 변경하기
df.loc['서준','체육'] = 80
df

    수학  영어   음악  체육  국어
이름
서준  90  98   85  80  80
우현  80  89   95  90  80
인아  70  95  100  90  80
철수  10  20   30  40  50
영희  70  95  100  90  80

In [71]:
# 서준의 음악과 체육점수를 50점으로 변경하기
df.loc['서준',['음악','체육']] = 50
df

    수학  영어   음악  체육  국어
이름
서준  90  98   50  50  80
우현  80  89   95  90  80
인아  70  95  100  90  80
철수  10  20   30  40  50
영희  70  95  100  90  80

In [74]:
# 서준의 음악 점수를 100 점 체육점수를 50점으로 변경하기

df.loc['서준',['음악','체육']] = 100, 50
df

    수학  영어   음악  체육  국어
이름
서준  90  98  100  50  80
우현  80  89   95  90  80
인아  70  95  100  90  80
철수  10  20   30  40  50
영희  70  95  100  90  80

In [75]:
# = df.T
df.transpose()

이름   서준  우현   인아  철수   영희
수학   90  80   70  10   70
영어   98  89   95  20   95
음악  100  95  100  30  100
체육   50  90   90  40   90
국어   80  80   80  50   80

In [76]:
df.T

이름   서준  우현   인아  철수   영희
수학   90  80   70  10   70
영어   98  89   95  20   95
음악  100  95  100  30  100
체육   50  90   90  40   90
국어   80  80   80  50   80

In [150]:
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

df = pd.DataFrame(dict_data, index=['r0','r1','r2'])

In [151]:
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [152]:
# 인덱스 재설정하기

new_index = ['r0','r1' ,'r2', 'r3', 'r4']
ndf = df.reindex(new_index, fill_value=0)    ## Nan 처리
ndf

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
r3   0   0   0   0   0
r4   0   0   0   0   0

In [153]:
ndf = df.reset_index()
ndf

  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15

In [154]:
# 내림차순으로 행 인덱스 정렬
df.sort_index(ascending=False)

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

In [155]:
df.sort_values(by='c1', ascending=False, inplace=True)

In [156]:
df

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

### DataFrame 연산

In [130]:
import seaborn as sns

In [131]:
# 타이타닉 데이터 불러오기

titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [135]:
# titanic에서 age와 fare부분의 컬럼만 발췌하여 df라는 dataFrame 만들기
# df = titanic.loc[:,['age','fare']]
df = pd.DataFrame(titanic[['age','fare']])
df.head()

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [141]:
# 모든 컬럼을 10씩 증가하여 addition DataFrame 생성하기
addition = df + 10
addition.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [142]:
# addition과 df의 차를 구하여 subtraction이라는 Dataframe 만들기

subtraction = addition - df
subtraction.head()

    age  fare
0  10.0  10.0
1  10.0  10.0
2  10.0  10.0
3  10.0  10.0
4  10.0  10.0

In [ ]:
#