# DataFrame
- 2차원 배열
- 행과 열로 구성

In [1]:
import pandas as pd
# Dictionary를 이용한 DataFrame 생성
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}
dict_data

{'c0': [1, 2, 3],
 'c1': [4, 5, 6],
 'c2': [7, 8, 9],
 'c3': [10, 11, 12],
 'c4': [13, 14, 15]}

In [2]:
df = pd.DataFrame(dict_data)
df

   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [3]:
# List를 이용한 DataFrame 생성
df = pd.DataFrame(
    [[15, '남', '덕영중'],
    [17, '여', '수리중']],
    index = ['준서','예은'],
    columns=['나이','성별','학교']
    )
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [5]:
# 행과 열 이름 변경하기
print(df.index)
print(df.columns)

Index(['준서', '예은'], dtype='object')
Index(['나이', '성별', '학교'], dtype='object')

In [8]:
# 행 인덱스, 열 이름 변경하기 - 1
df.index = ['학생1', '학생2']
df.columns = ['연령','남녀','소속']
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [9]:
df = pd.DataFrame(
    [[15, '남', '덕영중'],
    [17, '여', '수리중']],
    index = ['준서','예은'],
    columns=['나이','성별','학교']
    )
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [12]:
df.rename(columns={'나이':'연령', '성별':'남녀', '학교':'소속'}, inplace=True) # 모든 컬럼에 적용**
df

    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [13]:
# 행 이름 변경하기
# df의 행 인덱스 중에서 '준서'를 '학생1'로, '예은'을 '학생2'로 바꾸기

df.rename(index={'준서':'학생1', '예은':'학생2' }, inplace=True)
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [16]:
df = pd.DataFrame(
                # 데이터
                [[90,98,85,100],
                [80,89,95,90],
                [70,95,100,90]],
                # 컬럼
                columns=['수학','영어','음악','체육'],
                # 행
                index=['서준','우현','인아']
                )
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [18]:
df = {'수학':[90,80,70], '영어':[98,89,95], '음악':[85,95,100], '체육':[100,90,90]}
df = pd.DataFrame(df, index=['서준','우현','인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

### 행삭제

In [27]:
df2 = df.copy()

In [28]:
df2

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [29]:
# df2의 index가 우현인 1개행을 삭제

df2.drop('우현', axis=0, inplace=True) # 결과 반영

In [30]:
df2

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [44]:
df3 = df.copy()

In [45]:
df3

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [47]:
# df3의 index가 우현과 인아인 2개 행을 삭제
df3.drop(['우현','인아'], axis=0, inplace=True)

In [50]:
# 열 삭제
df4 = df.copy()

In [51]:
df4

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [54]:
# df4의 수학 1개 열을 삭제
# axis='rows','column'
df4.drop('수학', axis=1, inplace=True)

In [55]:
df4

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [56]:
df5 = df.copy()

In [57]:
df5

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [60]:
df5.drop(['영어','음악'], axis=1, inplace=True)
df5

KeyError: "['영어' '음악'] not found in axis"

In [61]:
df5

    수학   체육
서준  90  100
우현  80   90
인아  70   90