# 서울시에서 일어나는 범죄와 체감 안전도
: 강남3구 안전도가 얼마나 되는지 또한 서울시 전체의 안전도가 얼마나 되는지 확인

In [2]:
import pandas as pd

In [6]:
crime_anal_police = pd.read_csv("../Data/crime_in_Seoul.csv", encoding="euc-kr")
crime_anal_police.head()

    관서명  살인 발생  살인 검거  강도 발생  강도 검거  강간 발생  강간 검거  절도 발생 절도 검거  폭력 발생  폭력 검거
0   중부서      2      2      3      2    105     65  1,395   477  1,355  1,170
1   종로서      3      3      6      5    115     98  1,070   413  1,278  1,070
2  남대문서      1      0      6      4     65     46  1,153   382    869    794
3  서대문서      2      2      5      4    154    124  1,812   738  2,056  1,711
4   혜화서      3      2      5      4     96     63  1,114   424  1,015    861

In [7]:
crime_anal_police.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   관서명     31 non-null     object
 1   살인 발생   31 non-null     int64
 2   살인 검거   31 non-null     int64
 3   강도 발생   31 non-null     int64
 4   강도 검거   31 non-null     int64
 5   강간 발생   31 non-null     int64
 6   강간 검거   31 non-null     int64
 7   절도 발생   31 non-null     object
 8   절도 검거   31 non-null     object
 9   폭력 발생   31 non-null     object
 10  폭력 검거   31 non-null     object
dtypes: int64(6), object(5)
memory usage: 2.8+ KB

In [8]:
crime_anal_police[crime_anal_police['관서명']=="강서서"]

    관서명  살인 발생  살인 검거  강도 발생  강도 검거  강간 발생  강간 검거  절도 발생  절도 검거  폭력 발생  폭력 검거
19  강서서      7      8     13     13    262    191  2,096  1,260  3,207  2,718

In [10]:
police_address = pd.read_csv("../Data/SeoulPoliceAddress.csv")
police_address.head()

       경찰관서           전화번호            FAX                  주소
0   서울중부경찰서  (02)2273-4400  (02)2275-3009        서울 중구 수표로 27
1   서울종로경찰서  (02)3701-4324  (02)3701-4223       서울 종로구 율곡로 46
2  서울남대문경찰서  (02)2096-8324  (02)2096-8337      서울 중구 한강대로 410
3  서울서대문경찰서   (02)335-8192   (02)335-8189     서울 서대문구 통일로 113
4   서울혜화경찰서   (02)762-4400  (02)3158-7133  서울 종로구 창경궁로 112-16

In [17]:
# Method 1

station_name = []

for i in crime_anal_police['관서명']:
    station_name.append("서울"+i[:-1]+"경찰서")

station_name

['서울중부경찰서',
 '서울종로경찰서',
 '서울남대문경찰서',
 '서울서대문경찰서',
 '서울혜화경찰서',
 '서울용산경찰서',
 '서울성북경찰서',
 '서울동대문경찰서',
 '서울마포경찰서',
 '서울영등포경찰서',
 '서울성동경찰서',
 '서울동작경찰서',
 '서울광진경찰서',
 '서울서부경찰서',
 '서울강북경찰서',
 '서울금천경찰서',
 '서울중랑경찰서',
 '서울강남경찰서',
 '서울관악경찰서',
 '서울강서경찰서',
 '서울강동경찰서',
 '서울종암경찰서',
 '서울구로경찰서',
 '서울서초경찰서',
 '서울양천경찰서',
 '서울송파경찰서',
 '서울노원경찰서',
 '서울방배경찰서',
 '서울은평경찰서',
 '서울도봉경찰서',
 '서울수서경찰서']

In [20]:
# Method 2

station_name = []
station_name = list("서울" + crime_anal_police['관서명'].str[:-1] + "경찰서")
station_name

['서울중부경찰서',
 '서울종로경찰서',
 '서울남대문경찰서',
 '서울서대문경찰서',
 '서울혜화경찰서',
 '서울용산경찰서',
 '서울성북경찰서',
 '서울동대문경찰서',
 '서울마포경찰서',
 '서울영등포경찰서',
 '서울성동경찰서',
 '서울동작경찰서',
 '서울광진경찰서',
 '서울서부경찰서',
 '서울강북경찰서',
 '서울금천경찰서',
 '서울중랑경찰서',
 '서울강남경찰서',
 '서울관악경찰서',
 '서울강서경찰서',
 '서울강동경찰서',
 '서울종암경찰서',
 '서울구로경찰서',
 '서울서초경찰서',
 '서울양천경찰서',
 '서울송파경찰서',
 '서울노원경찰서',
 '서울방배경찰서',
 '서울은평경찰서',
 '서울도봉경찰서',
 '서울수서경찰서']

In [21]:
# 경찰서 갯수 확인
len(station_name)

31

In [22]:
len(police_address)

31

In [23]:
import urllib.request

# client_id = ""
# client_secret = ""

# top 위도, 경도
lng = []
lat = []

# 기름 비싼 매장 10
for address in police_address['주소']:
    encText = urllib.parse.quote(address)
    url = "https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode?query=" + encText #JSON 형식
    request = urllib.request.Request(url)
    request.add_header("X-NCP-APIGW-API-KEY-ID",client_id)
    request.add_header("X-NCP-APIGW-API-KEY",client_secret)

    response = urllib.request.urlopen(request)
    rescode = response.getcode()

    # 200이면 정상
    if rescode == 200:
        response_body = response.read()
        enText = response_body.decode('utf-8')
    else:
        print("Error Code:" + rescode)

    import json
    data = json.loads(enText)

    lng.append(data['addresses'][0]['x'])
    lat.append(data['addresses'][0]['y'])

In [25]:
police_address['lng'] = lng
police_address['lat'] = lat

In [26]:
police_address.head()

,경찰관서,전화번호,FAX,주소,lng,lat
0,서울중부경찰서,(02)2273-4400,(02)2275-3009,서울 중구 수표로 27,126.9896139,37.5635144
1,서울종로경찰서,(02)3701-4324,(02)3701-4223,서울 종로구 율곡로 46,126.9849292,37.5755322
2,서울남대문경찰서,(02)2096-8324,(02)2096-8337,서울 중구 한강대로 410,126.9735627,37.5548186
3,서울서대문경찰서,(02)335-8192,(02)335-8189,서울 서대문구 통일로 113,126.9667851,37.5649018
4,서울혜화경찰서,(02)762-4400,(02)3158-7133,서울 종로구 창경궁로 112-16,126.9989318,37.5718764

In [27]:
# police_address.to_csv("../Data/SeoulPoliceAddress_lating.csv", index=False)

In [28]:
# 2개의 File에 경찰관서 동일한 이름인지 확인
len(station_name == police_address['경찰관서']) # 글자와 순서가 동일

31

In [47]:
# 경찰서의 주소중 구 이름만 추출하기
police_gu = police_address['주소'].str.split()
police_gu

0            [서울, 중구, 수표로, 27]
1           [서울, 종로구, 율곡로, 46]
2          [서울, 중구, 한강대로, 410]
3         [서울, 서대문구, 통일로, 113]
4      [서울, 종로구, 창경궁로, 112-16]
5        [서울, 용산구, 원효로89길, 24]
6          [서울, 성북구, 보문로, 170]
7      [서울, 동대문구, 약령시로21길, 29]
8         [서울, 마포구, 마포대로, 183]
9       [서울시, 영등포구, 국회대로, 608]
10        [서울, 성동구, 왕십리광장로, 9]
11        [서울, 동작구, 노량진로, 148]
12         [서울, 광진구, 자양로, 167]
13         [서울, 은평구, 통일로, 757]
14        [서울, 강북구, 오패산로, 406]
15      [서울, 관악구, 남부순환로, 1435]
16    [서울, 중랑구, 신내역로3길, 40-10]
17     [서울, 강남구, 테헤란로114길, 11]
18        [서울, 관악구, 관악로5길, 33]
19          [서울, 양천구, 화곡로, 73]
20          [서울, 강동구, 성내로, 57]
21         [서울, 성북구, 종암로, 135]
22        [서울, 구로구, 가마산로, 235]
23        [서울, 서초구, 반포대로, 179]
24         [서울, 양천구, 목동동로, 99]
25         [서울, 송파구, 중대로, 221]
26         [서울, 노원구, 노원로, 283]
27        [서울, 서초구, 동작대로, 204]
28         [서울, 은평구, 연서로, 365]
29         [서울, 도봉구, 노해로, 403]
30         [서울, 강남구, 개포로, 617]
Name: 주소, dtype: object

In [42]:
police_gu = police_gu.str.get(1)

In [43]:
police_gu

0       중구
1      종로구
2       중구
3     서대문구
4      종로구
5      용산구
6      성북구
7     동대문구
8      마포구
9     영등포구
10     성동구
11     동작구
12     광진구
13     은평구
14     강북구
15     관악구
16     중랑구
17     강남구
18     관악구
19     양천구
20     강동구
21     성북구
22     구로구
23     서초구
24     양천구
25     송파구
26     노원구
27     서초구
28     은평구
29     도봉구
30     강남구
Name: 주소, dtype: object

In [44]:
crime_anal_police['구별'] = police_gu

In [45]:
crime_anal_police.head()

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,중부서,2,2,3,2,105,65,"1,395",477,"1,355","1,170",중구
1,종로서,3,3,6,5,115,98,"1,070",413,"1,278","1,070",종로구
2,남대문서,1,0,6,4,65,46,"1,153",382,869,794,중구
3,서대문서,2,2,5,4,154,124,"1,812",738,"2,056","1,711",서대문구
4,혜화서,3,2,5,4,96,63,"1,114",424,"1,015",861,종로구