# 서울시에서 일어나는 범죄와 체감 안전도
: 강남3구 안전도가 얼마나 되는지 또한 서울시 전체의 안전도가 얼마나 되는지 확인

In [54]:
import pandas as pd

In [55]:
crime_anal_police = pd.read_csv("../Data/crime_in_Seoul.csv", encoding="euc-kr")
crime_anal_police.head()

    관서명  살인 발생  살인 검거  강도 발생  강도 검거  강간 발생  강간 검거  절도 발생 절도 검거  폭력 발생  폭력 검거
0   중부서      2      2      3      2    105     65  1,395   477  1,355  1,170
1   종로서      3      3      6      5    115     98  1,070   413  1,278  1,070
2  남대문서      1      0      6      4     65     46  1,153   382    869    794
3  서대문서      2      2      5      4    154    124  1,812   738  2,056  1,711
4   혜화서      3      2      5      4     96     63  1,114   424  1,015    861

In [56]:
crime_anal_police.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   관서명     31 non-null     object
 1   살인 발생   31 non-null     int64
 2   살인 검거   31 non-null     int64
 3   강도 발생   31 non-null     int64
 4   강도 검거   31 non-null     int64
 5   강간 발생   31 non-null     int64
 6   강간 검거   31 non-null     int64
 7   절도 발생   31 non-null     object
 8   절도 검거   31 non-null     object
 9   폭력 발생   31 non-null     object
 10  폭력 검거   31 non-null     object
dtypes: int64(6), object(5)
memory usage: 2.8+ KB

In [57]:
crime_anal_police[crime_anal_police['관서명']=="강서서"]

    관서명  살인 발생  살인 검거  강도 발생  강도 검거  강간 발생  강간 검거  절도 발생  절도 검거  폭력 발생  폭력 검거
19  강서서      7      8     13     13    262    191  2,096  1,260  3,207  2,718

In [58]:
police_address = pd.read_csv("../Data/SeoulPoliceAddress.csv")
police_address.head()

       경찰관서           전화번호            FAX                  주소
0   서울중부경찰서  (02)2273-4400  (02)2275-3009        서울 중구 수표로 27
1   서울종로경찰서  (02)3701-4324  (02)3701-4223       서울 종로구 율곡로 46
2  서울남대문경찰서  (02)2096-8324  (02)2096-8337      서울 중구 한강대로 410
3  서울서대문경찰서   (02)335-8192   (02)335-8189     서울 서대문구 통일로 113
4   서울혜화경찰서   (02)762-4400  (02)3158-7133  서울 종로구 창경궁로 112-16

In [59]:
# Method 1

station_name = []

for i in crime_anal_police['관서명']:
    station_name.append("서울"+i[:-1]+"경찰서")

station_name

['서울중부경찰서',
 '서울종로경찰서',
 '서울남대문경찰서',
 '서울서대문경찰서',
 '서울혜화경찰서',
 '서울용산경찰서',
 '서울성북경찰서',
 '서울동대문경찰서',
 '서울마포경찰서',
 '서울영등포경찰서',
 '서울성동경찰서',
 '서울동작경찰서',
 '서울광진경찰서',
 '서울서부경찰서',
 '서울강북경찰서',
 '서울금천경찰서',
 '서울중랑경찰서',
 '서울강남경찰서',
 '서울관악경찰서',
 '서울강서경찰서',
 '서울강동경찰서',
 '서울종암경찰서',
 '서울구로경찰서',
 '서울서초경찰서',
 '서울양천경찰서',
 '서울송파경찰서',
 '서울노원경찰서',
 '서울방배경찰서',
 '서울은평경찰서',
 '서울도봉경찰서',
 '서울수서경찰서']

In [60]:
# Method 2

station_name = []
station_name = list("서울" + crime_anal_police['관서명'].str[:-1] + "경찰서")
station_name

['서울중부경찰서',
 '서울종로경찰서',
 '서울남대문경찰서',
 '서울서대문경찰서',
 '서울혜화경찰서',
 '서울용산경찰서',
 '서울성북경찰서',
 '서울동대문경찰서',
 '서울마포경찰서',
 '서울영등포경찰서',
 '서울성동경찰서',
 '서울동작경찰서',
 '서울광진경찰서',
 '서울서부경찰서',
 '서울강북경찰서',
 '서울금천경찰서',
 '서울중랑경찰서',
 '서울강남경찰서',
 '서울관악경찰서',
 '서울강서경찰서',
 '서울강동경찰서',
 '서울종암경찰서',
 '서울구로경찰서',
 '서울서초경찰서',
 '서울양천경찰서',
 '서울송파경찰서',
 '서울노원경찰서',
 '서울방배경찰서',
 '서울은평경찰서',
 '서울도봉경찰서',
 '서울수서경찰서']

In [61]:
# 경찰서 갯수 확인
len(station_name)

31

In [62]:
len(police_address)

31

In [63]:
import urllib.request

# client_id = ""
# client_secret = ""

# top 위도, 경도
lng = []
lat = []

# 기름 비싼 매장 10
for address in police_address['주소']:
    encText = urllib.parse.quote(address)
    url = "https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode?query=" + encText #JSON 형식
    request = urllib.request.Request(url)
    request.add_header("X-NCP-APIGW-API-KEY-ID",client_id)
    request.add_header("X-NCP-APIGW-API-KEY",client_secret)

    response = urllib.request.urlopen(request)
    rescode = response.getcode()

    # 200이면 정상
    if rescode == 200:
        response_body = response.read()
        enText = response_body.decode('utf-8')
    else:
        print("Error Code:" + rescode)

    import json
    data = json.loads(enText)

    lng.append(data['addresses'][0]['x'])
    lat.append(data['addresses'][0]['y'])

In [64]:
police_address['lng'] = lng
police_address['lat'] = lat

In [65]:
police_address.head()

,경찰관서,전화번호,FAX,주소,lng,lat
0,서울중부경찰서,(02)2273-4400,(02)2275-3009,서울 중구 수표로 27,126.9896139,37.5635144
1,서울종로경찰서,(02)3701-4324,(02)3701-4223,서울 종로구 율곡로 46,126.9849292,37.5755322
2,서울남대문경찰서,(02)2096-8324,(02)2096-8337,서울 중구 한강대로 410,126.9735627,37.5548186
3,서울서대문경찰서,(02)335-8192,(02)335-8189,서울 서대문구 통일로 113,126.9667851,37.5649018
4,서울혜화경찰서,(02)762-4400,(02)3158-7133,서울 종로구 창경궁로 112-16,126.9989318,37.5718764

In [66]:
# police_address.to_csv("../Data/SeoulPoliceAddress_lating.csv", index=False)

In [67]:
# 2개의 File에 경찰관서 동일한 이름인지 확인
len(station_name == police_address['경찰관서']) # 글자와 순서가 동일

31

In [68]:
# 경찰서의 주소중 구 이름만 추출하기
# [region.split()[1] for region in police_address['주소']]
police_gu = police_address['주소'].str.split()
police_gu

0            [서울, 중구, 수표로, 27]
1           [서울, 종로구, 율곡로, 46]
2          [서울, 중구, 한강대로, 410]
3         [서울, 서대문구, 통일로, 113]
4      [서울, 종로구, 창경궁로, 112-16]
5        [서울, 용산구, 원효로89길, 24]
6          [서울, 성북구, 보문로, 170]
7      [서울, 동대문구, 약령시로21길, 29]
8         [서울, 마포구, 마포대로, 183]
9       [서울시, 영등포구, 국회대로, 608]
10        [서울, 성동구, 왕십리광장로, 9]
11        [서울, 동작구, 노량진로, 148]
12         [서울, 광진구, 자양로, 167]
13         [서울, 은평구, 통일로, 757]
14        [서울, 강북구, 오패산로, 406]
15      [서울, 관악구, 남부순환로, 1435]
16    [서울, 중랑구, 신내역로3길, 40-10]
17     [서울, 강남구, 테헤란로114길, 11]
18        [서울, 관악구, 관악로5길, 33]
19          [서울, 양천구, 화곡로, 73]
20          [서울, 강동구, 성내로, 57]
21         [서울, 성북구, 종암로, 135]
22        [서울, 구로구, 가마산로, 235]
23        [서울, 서초구, 반포대로, 179]
24         [서울, 양천구, 목동동로, 99]
25         [서울, 송파구, 중대로, 221]
26         [서울, 노원구, 노원로, 283]
27        [서울, 서초구, 동작대로, 204]
28         [서울, 은평구, 연서로, 365]
29         [서울, 도봉구, 노해로, 403]
30         [서울, 강남구, 개포로, 617]
Name: 주소, dtype: object

In [69]:
# police_gu = police_gu.str.get(1)

In [70]:
# police_gu

In [71]:
# crime_anal_police['구별'] = police_gu

In [72]:
# crime_anal_police.head()

In [73]:
# 주소중 2번째 단어의 끝에 '구' 이름만 출력하기
gu_name = []

for name in police_address['주소']:
    temp = name.split() # 주소를 공백으로 나누기
    temp_gu = [gu for gu in temp if gu[-1] == '구'][0] # 구로 끝나는 문자열만 temp_gu에 저장
    gu_name.append(temp_gu)

crime_anal_police['구별'] = gu_name
crime_anal_police.head()

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,중부서,2,2,3,2,105,65,"1,395",477,"1,355","1,170",중구
1,종로서,3,3,6,5,115,98,"1,070",413,"1,278","1,070",종로구
2,남대문서,1,0,6,4,65,46,"1,153",382,869,794,중구
3,서대문서,2,2,5,4,154,124,"1,812",738,"2,056","1,711",서대문구
4,혜화서,3,2,5,4,96,63,"1,114",424,"1,015",861,종로구

In [74]:
# unique는 DataFrame만 가지고 사용가능
len(gu_name)

31

In [75]:
# list의 중복값 확인

len(set(gu_name))

23

In [76]:
# 관서명과 구별 이름 확인
crime_anal_police.loc[:,['관서명','구별']]

     관서명    구별
0    중부서    중구
1    종로서   종로구
2   남대문서    중구
3   서대문서  서대문구
4    혜화서   종로구
5    용산서   용산구
6    성북서   성북구
7   동대문서  동대문구
8    마포서   마포구
9   영등포서  영등포구
10   성동서   성동구
11   동작서   동작구
12   광진서   광진구
13   서부서   은평구
14   강북서   강북구
15   금천서   관악구
16   중랑서   중랑구
17   강남서   강남구
18   관악서   관악구
19   강서서   양천구
20   강동서   강동구
21   종암서   성북구
22   구로서   구로구
23   서초서   서초구
24   양천서   양천구
25   송파서   송파구
26   노원서   노원구
27   방배서   서초구
28   은평서   은평구
29   도봉서   도봉구
30   수서서   강남구

In [85]:
# DataSet을 보면 금천서가 관악구로 편성되어 있는데 현재는 금천서는 금천구로 편성되어 있음
crime_anal_police[crime_anal_police['관서명']=="금천서"]
crime_anal_police.loc[crime_anal_police['관서명']=="금천서", ['구별']] = '금천구'
crime_anal_police[crime_anal_police['관서명']=="금천서"]

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
15,금천서,3,4,6,6,151,122,"1,567",888,"2,054","1,776",금천구

In [86]:
# DataSet을 보면 강서서가 양천구로 편성되어 있는데 현재는 강서서는 강서구로 편성되어 있음
crime_anal_police[crime_anal_police['관서명']=="강서서"]
crime_anal_police.loc[crime_anal_police['관서명']=="강서서", ['구별']] = '강서구'
crime_anal_police[crime_anal_police['관서명']=="강서서"]

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
19,강서서,7,8,13,13,262,191,"2,096","1,260","3,207","2,718",강서구

In [87]:
# 확인
len(crime_anal_police['구별'].unique())

25

In [88]:
# csv 저장
crime_anal_police.to_csv("../Data/Seoul_crime_include_gu_name.csv", index=False)

In [104]:
crime_anal_police.head()

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,중부서,2,2,3,2,105,65,"1,395",477,"1,355","1,170",중구
1,종로서,3,3,6,5,115,98,"1,070",413,"1,278","1,070",종로구
2,남대문서,1,0,6,4,65,46,"1,153",382,869,794,중구
3,서대문서,2,2,5,4,154,124,"1,812",738,"2,056","1,711",서대문구
4,혜화서,3,2,5,4,96,63,"1,114",424,"1,015",861,종로구

> 관서명도 데이터를 정리하는 것이 아니고 구별로 데이터를 정리해야 한다.

In [103]:
len(crime_anal_police)

31

In [91]:
import numpy as np

In [105]:
crime_anal_police.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   관서명     31 non-null     object
 1   살인 발생   31 non-null     int64
 2   살인 검거   31 non-null     int64
 3   강도 발생   31 non-null     int64
 4   강도 검거   31 non-null     int64
 5   강간 발생   31 non-null     int64
 6   강간 검거   31 non-null     int64
 7   절도 발생   31 non-null     object
 8   절도 검거   31 non-null     object
 9   폭력 발생   31 non-null     object
 10  폭력 검거   31 non-null     object
 11  구별      31 non-null     object
dtypes: int64(6), object(6)
memory usage: 3.0+ KB

In [110]:
crime_anal_police['절도 발생'] = crime_anal_police['절도 발생'].str.replace(',', '').astype(int)
crime_anal_police['절도 검거'] = crime_anal_police['절도 검거'].str.replace(',', '').astype(int)
crime_anal_police['폭력 발생'] = crime_anal_police['폭력 발생'].str.replace(',', '').astype(int)
crime_anal_police['폭력 검거'] = crime_anal_police['폭력 검거'].str.replace(',', '').astype(int)

In [111]:
crime_anal_police.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   관서명     31 non-null     object
 1   살인 발생   31 non-null     int64
 2   살인 검거   31 non-null     int64
 3   강도 발생   31 non-null     int64
 4   강도 검거   31 non-null     int64
 5   강간 발생   31 non-null     int64
 6   강간 검거   31 non-null     int64
 7   절도 발생   31 non-null     int64
 8   절도 검거   31 non-null     int64
 9   폭력 발생   31 non-null     int64
 10  폭력 검거   31 non-null     int64
 11  구별      31 non-null     object
dtypes: int64(10), object(2)
memory usage: 3.0+ KB

In [112]:
# 구별로 데이터를 정리한다.

crime_anal = pd.pivot_table(crime_anal_police, index='구별', aggfunc=np.sum)

In [113]:
crime_anal.head()

     강간 검거  강간 발생  강도 검거  강도 발생  살인 검거  살인 발생  절도 검거  절도 발생  폭력 검거  폭력 발생
구별
강남구    349    449     18     21     10     13   1650   3850   3705   4284
강동구    123    156      8      6      3      4    789   2366   2248   2712
강북구    126    153     13     14      8      7    618   1434   2348   2649
강서구    191    262     13     13      8      7   1260   2096   2718   3207
관악구    221    320     14     12      8      9    827   2706   2642   3298

In [114]:
len(crime_anal)

25

In [119]:

crime_anal['강간검거율'] = crime_anal['강간 검거'] / crime_anal['강간 발생'] * 100
crime_anal['강도검거율'] = crime_anal['강도 검거'] / crime_anal['강도 발생'] * 100
crime_anal['살인검거율'] = crime_anal['살인 검거'] / crime_anal['살인 발생'] * 100
crime_anal['절도검거율'] = crime_anal['절도 검거'] / crime_anal['절도 발생'] * 100
crime_anal['폭력검거율'] = crime_anal['폭력 검거'] / crime_anal['폭력 발생'] * 100

In [120]:
crime_anal.head()

,강간 검거,강간 발생,강도 검거,강도 발생,살인 검거,살인 발생,절도 검거,절도 발생,폭력 검거,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,,,,,,
강남구,349,449,18,21,10,13,1650,3850,3705,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,123,156,8,6,3,4,789,2366,2248,2712,78.846154,133.333333,75.000000,33.347422,82.890855
강북구,126,153,13,14,8,7,618,1434,2348,2649,82.352941,92.857143,114.285714,43.096234,88.637222
강서구,191,262,13,13,8,7,1260,2096,2718,3207,72.900763,100.000000,114.285714,60.114504,84.752105
관악구,221,320,14,12,8,9,827,2706,2642,3298,69.062500,116.666667,88.888889,30.561715,80.109157

In [121]:
# 검거 건수는 삭제
del crime_anal['강간 검거']
del crime_anal['강도 검거']
del crime_anal['살인 검거']
del crime_anal['절도 검거']
del crime_anal['폭력 검거']

crime_anal

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,133.333333,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,114.285714,43.096234,88.637222
강서구,262,13,7,2096,3207,72.900763,100.000000,114.285714,60.114504,84.752105
관악구,320,12,9,2706,3298,69.062500,116.666667,88.888889,30.561715,80.109157
광진구,240,14,4,3026,2625,91.666667,185.714286,100.000000,42.200925,83.047619
구로구,281,15,8,2335,3007,58.362989,73.333333,75.000000,38.072805,80.877951
금천구,151,6,3,1567,2054,80.794702,100.000000,133.333333,56.668794,86.465433
노원구,197,7,10,2193,2723,61.421320,100.000000,100.000000,36.525308,85.530665
도봉구,102,9,3,1063,1487,103.921569,111.111111,100.000000,44.967074,87.626093
동대문구,173,13,5,1981,2548,84.393064,100.000000,100.000000,41.090358,87.401884
동작구,285,9,5,1865,1910,48.771930,55.555556,100.000000,35.442359,83.089005
마포구,294,14,8,2555,2983,84.013605,71.428571,100.000000,31.819961,84.445189
서대문구,154,5,2,1812,2056,80.519481,80.000000,100.000000,40.728477,83.219844
서초구,393,9,8,2635,2399,63.358779,66.666667,75.000000,41.404175,87.453105
성동구,126,9,4,1607,1612,94.444444,88.888889,100.000000,37.149969,86.538462
성북구,150,5,5,1785,2209,82.666667,80.000000,100.000000,41.512605,83.974649
송파구,220,13,11,3239,3295,80.909091,76.923077,90.909091,34.856437,84.552352
양천구,120,6,3,1890,2509,87.500000,50.000000,166.666667,35.555556,80.908729
영등포구,295,22,14,2964,3572,62.033898,90.909091,85.714286,32.995951,82.894737
용산구,194,14,5,1557,2050,89.175258,100.000000,100.000000,37.700706,83.121951
은평구,166,9,3,1914,2653,84.939759,66.666667,100.000000,37.147335,86.920467
종로구,211,11,6,2184,2293,76.303318,81.818182,83.333333,38.324176,84.212822
중구,170,9,3,2548,2224,65.294118,66.666667,66.666667,33.712716,88.309353
중랑구,187,11,13,2135,2847,79.144385,81.818182,92.307692,38.829040,84.545135