In [ ]:
# 19대 대선 테이블 추가 쿼리
# CREATE TABLE `education`.`election` (
#   `seq` INT NOT NULL,
#   `region` VARCHAR(45) NULL,
#   `city` VARCHAR(45) NULL,
#   `population` INT NULL,
#   `moonVote` INT NULL,
#   `hongVote` INT NULL,
#   `ahnVote` INT NULL,
#   PRIMARY KEY (`seq`));

# region : 서울특별시, 경기도 등과 같은 광역시도를 나타낸다.
# city : 광역시도 내의 시군구를 나타낸다(강북구, 성북구, 강남구, ...)
# pop : 각 광역시도별 시군구의 총 인구수를 나타내준다.
# moonVote : 19대 대선 후보인 문재인 전 대선 후보의 해당 지역 투표수 데이터를 나타낸다.
# hongVote : 19대 대선 후보인 홍준표 전 대선 후보의 해당 지역 투표수 데이터를 나타낸다.
# ahnVote : 19대 대선 후보인 안철수 전 대선 후보의 해당 지역 투표수 데이터를 나타낸다.
# 각 대선 후보 상위 3명의 투표수 데이터를 통해 지역별 후보 선호도 및 투표율 등의 정보를 도출해내기 위해 필요하다.

In [12]:
import pandas as pd
# 2017년 대선 자료 불러오기
column = ['seq','region','city','population','moonVote','hongVote','ahnVote']
election = pd.read_csv("../Data/election_2017.csv")
election.columns = column
election

     seq   region  city  population  moonVote  hongVote  ahnVote
0      0    서울특별시   종로구      102566     42512     22325    22313
1      1    서울특별시    중구       82852     34062     17901    19372
2      2    서울특별시   용산구      148157     58081     35230    32109
3      3    서울특별시   성동구      203175     86686     40566    45674
4      4    서울특별시   광진구      240030    105512     46368    52824
..   ...      ...   ...         ...       ...       ...      ...
245  245     경상남도   산청군       24513      6561     12544     2753
246  246     경상남도   거창군       41325     11256     19976     4923
247  247     경상남도   합천군       33021      7143     19699     3077
248  248  제주특별자치도   제주시      273163    125717     48027    55971
249  249  제주특별자치도  서귀포시      101296     43776     20036    21890

[250 rows x 7 columns]

In [22]:
import pymysql
import pandas as pd
from sqlalchemy import create_engine

In [23]:
# Connection
conn = pymysql.connect(host="127.0.0.1", user="root", password="qwer1234", \
                        db = "education", charset="utf8")

In [25]:
engine = create_engine("mysql+pymysql://root:qwer1234@127.0.0.1:3306/education")
conn = engine.connect()

In [26]:
election.to_sql(name="election", con=engine, if_exists='append', index=False)

In [27]:
election = pd.read_sql_table('election', conn)
election.head()

   seq region city  population  moonVote  hongVote  ahnVote
0    0  서울특별시  종로구      102566     42512     22325    22313
1    1  서울특별시   중구       82852     34062     17901    19372
2    2  서울특별시  용산구      148157     58081     35230    32109
3    3  서울특별시  성동구      203175     86686     40566    45674
4    4  서울특별시  광진구      240030    105512     46368    52824