In [1]:
import pandas as pd
data = pd.read_csv("../Data/gpascore.csv")
data.head()

   admit    gre   gpa  rank
0      0  380.0  3.21     3
1      1  660.0  3.67     3
2      1  800.0  4.00     1
3      1  640.0  3.19     4
4      0  520.0  2.33     4

admit : 합격여부    
gre : 영어성적      
gpa : 학점   
rank : 지원한 대학원 수준

### Preprocessing(전처리)

In [4]:
# 결측치 처리
data.isnull().sum()

admit    0
gre      0
gpa      0
rank     0
dtype: int64

In [3]:
# 결측치 데이터 삭제
data.dropna(inplace=True)

# 결측치 데이터를 다른값으로 대체
# data.fillna(100)

In [6]:
# rank의 종류 파악
sorted(data['rank'].unique())

[1, 2, 3, 4]

In [7]:
# 영어 점수의 최소값과 최대값
print('최대값 :', data['gre'].max())
print('최소값 :', data['gre'].min())

최대값 : 800.0
최소값 : 220.0

In [9]:
# Training Data
x = data[['gre', 'gpa', 'rank']]
x.head()

     gre   gpa  rank
0  380.0  3.21     3
1  660.0  3.67     3
2  800.0  4.00     1
3  640.0  3.19     4
4  520.0  2.33     4

In [10]:
# target Data
y = data['admit']
y.head()

0    0
1    1
2    1
3    1
4    0
Name: admit, dtype: int64

In [11]:
x.count()

gre     425
gpa     425
rank    425
dtype: int64