# 데이터 베이스
- 규모가 크지 않은 데이터라면 csv와 json형식으로 사용해도 문제는 없음.
- 데이터 규모가 굉장히 크거나 복잡하면 데이터베이스를 사용하는 것이 원리

### 장점
- 데이터와 관련된 모든 처리를 하나의 소프트웨어로 할 수 있음
- 여러 데이터의 속성을 연관시키며 저장 가능.
- 중복된 데이터를 허용하지 앟는 제약을 둘 수 있음.
- 데이터의 정합성을 확보.
- 데이터에 동시 접근했을 경우 문제 처리.
- 대량의 데이터를 조금씩 읽어 사용 할 수 있으며 정렬 등도 쉽게 처리함.

### SQLite
: 가볍게 파일 하나로 사용할 수 있는 데이터베이스

In [3]:
import sqlite3

# sqlite Database에 연결하기
dbpath = "../Data/test.sqlite"
conn = sqlite3.connect(dbpath)

# 테이블을 생성하고 데이터 넣기
curs = conn.cursor()
curs.executescript(
    """
    /* item 테이블이 이미 있다면 제거 */
    DROP TABLE IF EXISTS items;
    /* 테이블 생성하기 */
    CREATE TABLE items(
        item_id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT UNIQUE,
        price INTEGER
    );

    /* 데이터 넣기 */
    INSERT INTO items(name, price) VALUES('Apple', 800);
    INSERT INTO items(name, price) VALUES('Orange', 780);
    INSERT INTO items(name, price) VALUES('Banana', 430);
    """

)

In [4]:
# 위의 조작을 데이터베이스에 반영하기
conn.commit()

In [5]:
# 데이터 추출하기 
curs = conn.cursor()
curs.execute("SELECT item_id, name, price FROM items")
item_list = curs.fetchall()

# 출력하기
for it in item_list:
    print(it)

    # 튜플형태로 출력됨

(1, 'Apple', 800)
(2, 'Orange', 780)
(3, 'Banana', 430)

In [6]:
# 데이터 넣기
curs = conn.cursor()
curs.execute("INSERT INTO items (name, price) VALUES (?,?)", ("Mango", 5200))
conn.commit()

In [7]:
# 여러 데이터를 연속으로 넣기
curs = conn.cursor()
data = [("Kiwi", 4000), ("Grape", 8000)]
curs.executemany("INSERT INTO items (name, price) VALUES (?,?)", data)
conn.commit()

In [8]:
# 4000 ~ 7000원 사이의 데이터 추출하기

curs = conn.cursor()
price_range = (4000, 7000)
curs.execute("SELECT * FROM items WHERE price between ? AND ?", price_range)
item_list = curs.fetchall()

# 출력하기
for it in item_list:
    print(it)

(4, 'Mango', 5200)
(5, 'Kiwi', 4000)

---
# MySQL 연결

In [9]:
# !pip install pymysql

In [10]:
import pymysql

In [11]:
# Connection
conn = pymysql.connect(host="127.0.0.1", user="root", password="qwer1234", \
                        db = "education", charset="utf8")

In [12]:
# Connection으로 부터 Cursor 생성
curs = conn.cursor()

In [13]:
sql = "select * from student"
curs.execute(sql)

19

In [14]:
# Data Fetch
rows = curs.fetchall()
print(rows)

(('b002', '관우1', '심리학과1', '010-222', '서울'), ('b003', '장비', '경제학과', '010-333', '서울'), ('c001', '조조', '국문학과', '016-111', '경기'), ('c002', '여포', '심리학과', '016-222', '경기'), ('c003', '손견', '경제학과', '016-333', '경기'), ('d001', '홍길동', '수학과', '017-001', '광주'), ('S001', '박소명', '컴퓨터공학과', '123-4567', None), ('S002', '최민국', '컴퓨터공학과', '234-5678', None), ('S003', '이승호', '국문학과', '345-6789', None), ('S004', '정수봉', '국문학과', '456-7890', None), ('S005', '김상진', '사학과', '567-8901', None), ('S006', '황정숙', '사학과', '678-9012', None), ('S010', 'Jam', 'Computer', '1234', None), ('S013', '연습', '화학', '555', None), ('S100', '12', '1', '1', None), ('S999', '홍길동', '컴공', '123', None), ('w001', '조조', '국문학과', '016-111', '경기'), ('w002', '여포', '심리학과', '016-222', '경기'), ('w003', '손건', '경제학과', '016-333', '경기'))

In [15]:
# Connection 종료

conn.close()

In [16]:
# list로 변환
rowList = list(rows)
print(rowList)

[('b002', '관우1', '심리학과1', '010-222', '서울'), ('b003', '장비', '경제학과', '010-333', '서울'), ('c001', '조조', '국문학과', '016-111', '경기'), ('c002', '여포', '심리학과', '016-222', '경기'), ('c003', '손견', '경제학과', '016-333', '경기'), ('d001', '홍길동', '수학과', '017-001', '광주'), ('S001', '박소명', '컴퓨터공학과', '123-4567', None), ('S002', '최민국', '컴퓨터공학과', '234-5678', None), ('S003', '이승호', '국문학과', '345-6789', None), ('S004', '정수봉', '국문학과', '456-7890', None), ('S005', '김상진', '사학과', '567-8901', None), ('S006', '황정숙', '사학과', '678-9012', None), ('S010', 'Jam', 'Computer', '1234', None), ('S013', '연습', '화학', '555', None), ('S100', '12', '1', '1', None), ('S999', '홍길동', '컴공', '123', None), ('w001', '조조', '국문학과', '016-111', '경기'), ('w002', '여포', '심리학과', '016-222', '경기'), ('w003', '손건', '경제학과', '016-333', '경기')]

In [17]:
# data type 확인

type(rowList)

list

In [18]:
# 필요한 부분 데이터 빼오기
print(rowList[0])
print(rowList[0][1])

('b002', '관우1', '심리학과1', '010-222', '서울')
관우1

# Insert Data#1

In [19]:
# Connection
conn = pymysql.connect(host="127.0.0.1", user="root", password="qwer1234", \
                        db = "education", charset="utf8")

In [20]:
# Connection 으로 부터 Cursur 생성
curs = conn.cursor()

In [21]:
# SQL문장
sql = "insert into student (scode, sname, sdept, sphone, saddress) values(%s, %s, %s, %s, %s)"

In [22]:
curs.execute(sql, ('d008','유비','국문학과','010-1111','서울'))
curs.execute(sql, ('d009','관우','심리학과','010-2222','서울'))
curs.execute(sql, ('d010','장비','경제학과','010-3333','서울'))

1

# Insert Data#2

In [23]:
# Connection
conn = pymysql.connect(host="127.0.0.1", user="root", password="qwer1234", \
    db = "education", charset="utf8")

In [24]:
curs = conn.cursor()

In [25]:
data = (
    ('w001', '조조', '국문학과', '016-111', '경기'),
    ('w002', '여포', '심리학과', '016-222', '경기'),
    ('w003', '손건', '경제학과', '016-333', '경기')
)

In [26]:
# SQL문장
sql = "insert into student (scode, sname, sdept, sphone, saddress) values(%s, %s, %s, %s, %s)"

In [27]:
curs.executemany(sql, data)

IntegrityError: (1062, "Duplicate entry 'w001' for key 'PRIMARY'")

In [28]:
conn.commit()

---
# select의 내용을 dataFrame으로 보기

In [29]:
# !pip install sqlalchemy

In [30]:
import pandas as pd
from sqlalchemy import create_engine

In [31]:
engine = create_engine("mysql+pymysql://root:qwer1234@127.0.0.1:3306/education")
conn = engine.connect()

In [32]:
data = pd.read_sql_table('student', conn)
data

   scode sname     sdept    sphone saddress
0   b002   관우1     심리학과1   010-222       서울
1   b003    장비      경제학과   010-333       서울
2   c001    조조      국문학과   016-111       경기
3   c002    여포      심리학과   016-222       경기
4   c003    손견      경제학과   016-333       경기
5   d001   홍길동       수학과   017-001       광주
6   S001   박소명    컴퓨터공학과  123-4567     None
7   S002   최민국    컴퓨터공학과  234-5678     None
8   S003   이승호      국문학과  345-6789     None
9   S004   정수봉      국문학과  456-7890     None
10  S005   김상진       사학과  567-8901     None
11  S006   황정숙       사학과  678-9012     None
12  S010   Jam  Computer      1234     None
13  S013    연습        화학       555     None
14  S100    12         1         1     None
15  S999   홍길동        컴공       123     None
16  w001    조조      국문학과   016-111       경기
17  w002    여포      심리학과   016-222       경기
18  w003    손건      경제학과   016-333       경기

In [33]:
conn.close()

---
### dataFrame을 Database로 Insert 하기

In [34]:
column = ['rank','title']
movies = pd.read_csv("../Data/DaumList.csv")
movies.columns = column
movies.head()

   rank                        title
0     1                      탑건: 매버릭
1     2  마녀(魔女) Part2. The Other One
2     3                       범죄도시 2
3     4                          브로커
4     5                     버즈 라이트이어

In [35]:
engine = create_engine("mysql+pymysql://root:qwer1234@127.0.0.1:3306/daum")
conn = engine.connect()

In [36]:
movies.to_sql(name="movie", con=engine, if_exists='append', index=False)

KeyboardInterrupt:

In [ ]:
daum = pd.read_sql_table('movie', conn)
daum

    rank                           title
0      1                         탑건: 매버릭
1      2     마녀(魔女) Part2. The Other One
2      3                          범죄도시 2
3      4                             브로커
4      5                        버즈 라이트이어
5      6                    쥬라기 월드: 도미니언
6      7           극장판 윌벤져스 : 수상한 캠핑 대소동
7      8  극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미
8      9                          헤어질 결심
9     10                           룸 쉐어링
10    11                  니 부모 얼굴이 보고 싶다
11    12                          로스트 시티
12    13                              모어
13    14                             니얼굴
14    15                           애프터 양

In [63]:
# ridibooks 테이블 정보를 넣어서 가져오기


import pandas as pd

column = ['rank','title', 'content']
ridibooks = pd.read_csv("../Data/ridibookList.csv")
ridibooks.columns = column
len(ridibooks)

200

In [ ]:
# Connection
conn = pymysql.connect(host="127.0.0.1", user="root", password="qwer1234", \
                        db = "daum", charset="utf8")

In [ ]:
curs = conn.cursor()

In [ ]:
sql = "select * from ridibooks"
curs.execute(sql)

0

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
# 
engine = create_engine("mysql+pymysql://root:qwer1234@127.0.0.1:3306/daum")
conn = engine.connect()

In [ ]:
ridibooks.to_sql(name="ridibooks", con=engine, if_exists='append', index=False)

In [ ]:
ridiTable = pd.read_sql_table('ridibooks', conn)
ridiTable.head()

   rank         title                                            content
0     1           역행자  <역행자> 오타쿠 흙수저에서 월 1억 자동수익을 실현한 무자본 연쇄창업마,\r\n라...
1     2          작별인사  <작별인사> 누구도 도와줄 수 없는 상황, 혼자 헤쳐나가야 한다\r\n지켜야 할 약...
2     3  인플레이션에서 살아남기  <인플레이션에서 살아남기> \n\n40년 만에 찾아온 인플레의 역습, \r\n당신의...
3     4    변화하는 세계 질서  <변화하는 세계 질서> \n\n《원칙 Principles: Life & Work》으...
4     5          피스타운  <피스타운> -“여긴 너무 비현실적이야, 그렇지 않아?”\r\n-뭐든지 이룰 수 있...

In [39]:
# 기상 데이터 가져와서 데이터베이스에 저장하기(아까 했던거)
# 기상 데이터 크롤링 -> 데이터베이스 바로 저장?
#  city, tmef, wf, tmn, tmx

from bs4 import BeautifulSoup

import urllib.request as req

url = "http://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp?stnId=108"
res = req.urlopen(url)
soup = BeautifulSoup(res, "html.parser")

In [ ]:
# #location = soup.find_all("location")
# # 도시, 날짜, 날씨, tmn, tmx List
# cities = []
# time = []
# weather = []
# tmn = []
# tmx = []

# location = soup.find_all('location')
# print(location)
# # tmef = location.find_all('tmef')
# # wf = location.find_all('wf')
# # tmn = location.find_all('tmn')
# # tmx = location.find_all('tmx')

# # for b,c,d,e in zip(tmef, wf, tmn, tmx):
# #    time.append(b.string)
# #    weather.append(c.string)
# #    tmn.append(d.string)
# #    tmx.append(e.string)

[<location wl_ver="3">
<province>서울ㆍ인천ㆍ경기도</province>
<city>서울</city>
<data>
<mode>A02</mode>
<tmef>2022-07-01 00:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>90</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-01 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>80</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 12:00</tmef>
<wf>구름많음</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 00:00</tmef>
<wf>구름많음</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 12:00</tmef>
<wf>구름많음</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 12:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>80</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-06 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-07 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-08 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
</location>, <location wl_ver="3">
<province>서울ㆍ인천ㆍ경기도</province>
<city>인천</city>
<data>
<mode>A02</mode>
<tmef>2022-07-01 00:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>27</tmx>
<reliability></reliability>
<rnst>90</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-01 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>27</tmx>
<reliability></reliability>
<rnst>80</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 12:00</tmef>
<wf>구름많음</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 00:00</tmef>
<wf>구름많음</wf>
<tmn>22</tmn>
<tmx>27</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 12:00</tmef>
<wf>구름많음</wf>
<tmn>22</tmn>
<tmx>27</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>27</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 12:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>27</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>27</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>27</tmx>
<reliability></reliability>
<rnst>80</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-06 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>27</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-07 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>27</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-08 00:00</tmef>
<wf>흐림</wf>
<tmn>22</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
</location>, <location wl_ver="3">
<province>서울ㆍ인천ㆍ경기도</province>
<city>수원</city>
<data>
<mode>A02</mode>
<tmef>2022-07-01 00:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>90</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-01 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>80</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 12:00</tmef>
<wf>구름많음</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 00:00</tmef>
<wf>구름많음</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 12:00</tmef>
<wf>구름많음</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 12:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>80</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-06 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-07 00:00</tmef>
<wf>흐림</wf>
<tmn>24</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-08 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
</location>, <location wl_ver="3">
<province>서울ㆍ인천ㆍ경기도</province>
<city>파주</city>
<data>
<mode>A02</mode>
<tmef>2022-07-01 00:00</tmef>
<wf>흐리고 비</wf>
<tmn>22</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>90</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-01 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>22</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>80</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 00:00</tmef>
<wf>흐림</wf>
<tmn>22</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 12:00</tmef>
<wf>구름많음</wf>
<tmn>22</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 00:00</tmef>
<wf>구름많음</wf>
<tmn>21</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 12:00</tmef>
<wf>구름많음</wf>
<tmn>21</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 00:00</tmef>
<wf>흐림</wf>
<tmn>21</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 12:00</tmef>
<wf>흐림</wf>
<tmn>21</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>80</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-06 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-07 00:00</tmef>
<wf>흐림</wf>
<tmn>22</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-08 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
</location>, <location wl_ver="3">
<province>서울ㆍ인천ㆍ경기도</province>
<city>이천</city>
<data>
<mode>A02</mode>
<tmef>2022-07-01 00:00</tmef>
<wf>흐리고 비</wf>
<tmn>22</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>90</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-01 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>22</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>80</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 00:00</tmef>
<wf>흐림</wf>
<tmn>22</tmn>
<tmx>31</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 12:00</tmef>
<wf>구름많음</wf>
<tmn>22</tmn>
<tmx>31</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 00:00</tmef>
<wf>구름많음</wf>
<tmn>22</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 12:00</tmef>
<wf>구름많음</wf>
<tmn>22</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 00:00</tmef>
<wf>흐림</wf>
<tmn>22</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 12:00</tmef>
<wf>흐림</wf>
<tmn>22</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 00:00</tmef>
<wf>흐림</wf>
<tmn>22</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>22</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>80</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-06 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-07 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-08 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
</location>, <location wl_ver="3">
<province>서울ㆍ인천ㆍ경기도</province>
<city>평택</city>
<data>
<mode>A02</mode>
<tmef>2022-07-01 00:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>31</tmx>
<reliability></reliability>
<rnst>90</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-01 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>31</tmx>
<reliability></reliability>
<rnst>80</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>32</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 12:00</tmef>
<wf>구름많음</wf>
<tmn>23</tmn>
<tmx>32</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 00:00</tmef>
<wf>구름많음</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 12:00</tmef>
<wf>구름많음</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 12:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>80</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-06 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-07 00:00</tmef>
<wf>흐림</wf>
<tmn>24</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-08 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>32</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
</location>, <location wl_ver="3">
<province>강원도영서</province>
<city>춘천</city>
<data>
<mode>A02</mode>
<tmef>2022-07-01 00:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>90</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-01 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>80</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 12:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 00:00</tmef>
<wf>구름많음</wf>
<tmn>22</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 12:00</tmef>
<wf>흐림</wf>
<tmn>22</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 12:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>80</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-06 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-07 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-08 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
</location>, <location wl_ver="3">
<province>강원도영서</province>
<city>원주</city>
<data>
<mode>A02</mode>
<tmef>2022-07-01 00:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>90</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-01 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>80</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 12:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 00:00</tmef>
<wf>구름많음</wf>
<tmn>22</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 12:00</tmef>
<wf>흐림</wf>
<tmn>22</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 12:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>80</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-06 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-07 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-08 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
</location>, <location wl_ver="3">
<province>강원도영동</province>
<city>강릉</city>
<data>
<mode>A02</mode>
<tmef>2022-07-01 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-01 12:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 00:00</tmef>
<wf>구름많음</wf>
<tmn>24</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 12:00</tmef>
<wf>구름많음</wf>
<tmn>24</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 00:00</tmef>
<wf>구름많음</wf>
<tmn>24</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 12:00</tmef>
<wf>구름많음</wf>
<tmn>24</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 00:00</tmef>
<wf>흐림</wf>
<tmn>24</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 12:00</tmef>
<wf>흐림</wf>
<tmn>24</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>70</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-06 00:00</tmef>
<wf>흐림</wf>
<tmn>24</tmn>
<tmx>31</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-07 00:00</tmef>
<wf>흐림</wf>
<tmn>24</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-08 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
</location>, <location wl_ver="3">
<province>대전ㆍ세종ㆍ충청남도</province>
<city>대전</city>
<data>
<mode>A02</mode>
<tmef>2022-07-01 00:00</tmef>
<wf>구름많음</wf>
<tmn>24</tmn>
<tmx>31</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-01 12:00</tmef>
<wf>흐림</wf>
<tmn>24</tmn>
<tmx>31</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 00:00</tmef>
<wf>구름많음</wf>
<tmn>24</tmn>
<tmx>32</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-02 12:00</tmef>
<wf>구름많음</wf>
<tmn>24</tmn>
<tmx>32</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 00:00</tmef>
<wf>구름많음</wf>
<tmn>23</tmn>
<tmx>31</tmx>
<reliability></reliability>
<rnst>30</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-03 12:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>31</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 00:00</tmef>
<wf>흐림</wf>
<tmn>24</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-04 12:00</tmef>
<wf>흐림</wf>
<tmn>24</tmn>
<tmx>29</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 00:00</tmef>
<wf>흐림</wf>
<tmn>24</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A02</mode>
<tmef>2022-07-05 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>24</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>90</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-06 00:00</tmef>
<wf>흐림</wf>
<tmn>24</tmn>
<tmx>31</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-07 00:00</tmef>
<wf>흐림</wf>
<tmn>24</tmn>
<tmx>30</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
<data>
<mode>A01</mode>
<tmef>2022-07-08 00:00</tmef>
<wf>흐림</wf>
<tmn>24</tmn>
<tmx>31</tmx>
<reliability></reliability>
<rnst>40</rnst>
</data>
</location>, <location wl_ver="3">
<province>대전ㆍ세종ㆍ충청남도</province>
<city>세종</city>

In [40]:
# 도시 출력
for i in soup.find_all("location"):
    print(i.find("city"))

<city>서울</city>
<city>인천</city>
<city>수원</city>
<city>파주</city>
<city>이천</city>
<city>평택</city>
<city>춘천</city>
<city>원주</city>
<city>강릉</city>
<city>대전</city>
<city>세종</city>
<city>홍성</city>
<city>청주</city>
<city>충주</city>
<city>영동</city>
<city>광주</city>
<city>목포</city>
<city>여수</city>
<city>순천</city>
<city>광양</city>
<city>나주</city>
<city>전주</city>
<city>군산</city>
<city>정읍</city>
<city>남원</city>
<city>고창</city>
<city>무주</city>
<city>부산</city>
<city>울산</city>
<city>창원</city>
<city>진주</city>
<city>거창</city>
<city>통영</city>
<city>대구</city>
<city>안동</city>
<city>포항</city>
<city>경주</city>
<city>울진</city>
<city>울릉도</city>
<city>제주</city>
<city>서귀포</city>

In [ ]:
# 서울로 테스트
seoul = soup.find("location")
seoul
for i in seoul.find_all("data"):
    print(i.find("tmef"))
    print(i.find("wf"))
    print(i.find("tmn"))
    print(i.find("tmx"))

<tmef>2022-07-01 00:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<tmef>2022-07-01 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<tmef>2022-07-02 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<tmef>2022-07-02 12:00</tmef>
<wf>구름많음</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<tmef>2022-07-03 00:00</tmef>
<wf>구름많음</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<tmef>2022-07-03 12:00</tmef>
<wf>구름많음</wf>
<tmn>23</tmn>
<tmx>30</tmx>
<tmef>2022-07-04 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<tmef>2022-07-04 12:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<tmef>2022-07-05 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<tmef>2022-07-05 12:00</tmef>
<wf>흐리고 비</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<tmef>2022-07-06 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>29</tmx>
<tmef>2022-07-07 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>28</tmx>
<tmef>2022-07-08 00:00</tmef>
<wf>흐림</wf>
<tmn>23</tmn>
<tmx>28</tmx>

In [41]:
# 도시별 날씨 데이터 구축
weather = {}

for i in soup.find_all("location"):
  # 키값을 만듦
  weather[i.find("city").text] = []
  for j in i.find_all("data"):
    temp = []
    temp.append(j.find("tmef").text)
    temp.append(j.find("wf").text)
    temp.append(j.find("tmn").text)
    temp.append(j.find("tmx").text)
    weather[i.find("city").text].append(temp)

In [42]:
# 키값 입력 하면 그 값만 나옴
print(weather['서울'])

[['2022-07-01 00:00', '흐리고 비', '23', '28'], ['2022-07-01 12:00', '흐리고 비', '23', '28'], ['2022-07-02 00:00', '흐림', '23', '29'], ['2022-07-02 12:00', '구름많음', '23', '29'], ['2022-07-03 00:00', '구름많음', '23', '30'], ['2022-07-03 12:00', '구름많음', '23', '30'], ['2022-07-04 00:00', '흐림', '23', '29'], ['2022-07-04 12:00', '흐림', '23', '29'], ['2022-07-05 00:00', '흐림', '23', '28'], ['2022-07-05 12:00', '흐리고 비', '23', '28'], ['2022-07-06 00:00', '흐림', '23', '29'], ['2022-07-07 00:00', '흐림', '23', '28'], ['2022-07-08 00:00', '흐림', '23', '28']]

In [43]:
# 현재 Dictionary로 되어 있어 List형태로 변환이 필요
tempList = []
for i in weather:
    for j in weather[i]:
        tempList.append([i, j[0], j[1], j[2], j[3]])

tempList

[['서울', '2022-07-01 00:00', '흐리고 비', '23', '28'],
 ['서울', '2022-07-01 12:00', '흐리고 비', '23', '28'],
 ['서울', '2022-07-02 00:00', '흐림', '23', '29'],
 ['서울', '2022-07-02 12:00', '구름많음', '23', '29'],
 ['서울', '2022-07-03 00:00', '구름많음', '23', '30'],
 ['서울', '2022-07-03 12:00', '구름많음', '23', '30'],
 ['서울', '2022-07-04 00:00', '흐림', '23', '29'],
 ['서울', '2022-07-04 12:00', '흐림', '23', '29'],
 ['서울', '2022-07-05 00:00', '흐림', '23', '28'],
 ['서울', '2022-07-05 12:00', '흐리고 비', '23', '28'],
 ['서울', '2022-07-06 00:00', '흐림', '23', '29'],
 ['서울', '2022-07-07 00:00', '흐림', '23', '28'],
 ['서울', '2022-07-08 00:00', '흐림', '23', '28'],
 ['인천', '2022-07-01 00:00', '흐리고 비', '23', '27'],
 ['인천', '2022-07-01 12:00', '흐리고 비', '23', '27'],
 ['인천', '2022-07-02 00:00', '흐림', '23', '28'],
 ['인천', '2022-07-02 12:00', '구름많음', '23', '28'],
 ['인천', '2022-07-03 00:00', '구름많음', '22', '27'],
 ['인천', '2022-07-03 12:00', '구름많음', '22', '27'],
 ['인천', '2022-07-04 00:00', '흐림', '23', '27'],
 ['인천', '2022-07-04 12:00', '흐림', '23', '27'],
 ['인천', '2022-07-05 00:00', '흐림', '23', '27'],
 ['인천', '2022-07-05 12:00', '흐리고 비', '23', '27'],
 ['인천', '2022-07-06 00:00', '흐림', '23', '27'],
 ['인천', '2022-07-07 00:00', '흐림', '23', '27'],
 ['인천', '2022-07-08 00:00', '흐림', '22', '28'],
 ['수원', '2022-07-01 00:00', '흐리고 비', '23', '30'],
 ['수원', '2022-07-01 12:00', '흐리고 비', '23', '30'],
 ['수원', '2022-07-02 00:00', '흐림', '23', '30'],
 ['수원', '2022-07-02 12:00', '구름많음', '23', '30'],
 ['수원', '2022-07-03 00:00', '구름많음', '23', '29'],
 ['수원', '2022-07-03 12:00', '구름많음', '23', '29'],
 ['수원', '2022-07-04 00:00', '흐림', '23', '29'],
 ['수원', '2022-07-04 12:00', '흐림', '23', '29'],
 ['수원', '2022-07-05 00:00', '흐림', '23', '29'],
 ['수원', '2022-07-05 12:00', '흐리고 비', '23', '29'],
 ['수원', '2022-07-06 00:00', '흐림', '23', '29'],
 ['수원', '2022-07-07 00:00', '흐림', '24', '29'],
 ['수원', '2022-07-08 00:00', '흐림', '23', '29'],
 ['파주', '2022-07-01 00:00', '흐리고 비', '22', '28'],
 ['파주', '2022-07-01 12:00', '흐리고 비', '22', '28'],
 ['파주', '2022-07-02 00:00', '흐림', '22', '28'],
 ['파주', '2022-07-02 12:00', '구름많음', '22', '28'],
 ['파주', '2022-07-03 00:00', '구름많음', '21', '29'],
 ['파주', '2022-07-03 12:00', '구름많음', '21', '29'],
 ['파주', '2022-07-04 00:00', '흐림', '21', '28'],
 ['파주', '2022-07-04 12:00', '흐림', '21', '28'],
 ['파주', '2022-07-05 00:00', '흐림', '23', '28'],
 ['파주', '2022-07-05 12:00', '흐리고 비', '23', '28'],
 ['파주', '2022-07-06 00:00', '흐림', '23', '28'],
 ['파주', '2022-07-07 00:00', '흐림', '22', '28'],
 ['파주', '2022-07-08 00:00', '흐림', '23', '28'],
 ['이천', '2022-07-01 00:00', '흐리고 비', '22', '30'],
 ['이천', '2022-07-01 12:00', '흐리고 비', '22', '30'],
 ['이천', '2022-07-02 00:00', '흐림', '22', '31'],
 ['이천', '2022-07-02 12:00', '구름많음', '22', '31'],
 ['이천', '2022-07-03 00:00', '구름많음', '22', '30'],
 ['이천', '2022-07-03 12:00', '구름많음', '22', '30'],
 ['이천', '2022-07-04 00:00', '흐림', '22', '29'],
 ['이천', '2022-07-04 12:00', '흐림', '22', '29'],
 ['이천', '2022-07-05 00:00', '흐림', '22', '29'],
 ['이천', '2022-07-05 12:00', '흐리고 비', '22', '29'],
 ['이천', '2022-07-06 00:00', '흐림', '23', '30'],
 ['이천', '2022-07-07 00:00', '흐림', '23', '30'],
 ['이천', '2022-07-08 00:00', '흐림', '23', '30'],
 ['평택', '2022-07-01 00:00', '흐리고 비', '23', '31'],
 ['평택', '2022-07-01 12:00', '흐리고 비', '23', '31'],
 ['평택', '2022-07-02 00:00', '흐림', '23', '32'],
 ['평택', '2022-07-02 12:00', '구름많음', '23', '32'],
 ['평택', '2022-07-03 00:00', '구름많음', '23', '30'],
 ['평택', '2022-07-03 12:00', '구름많음', '23', '30'],
 ['평택', '2022-07-04 00:00', '흐림', '23', '30'],
 ['평택', '2022-07-04 12:00', '흐림', '23', '30'],
 ['평택', '2022-07-05 00:00', '흐림', '23', '30'],
 ['평택', '2022-07-05 12:00', '흐리고 비', '23', '30'],
 ['평택', '2022-07-06 00:00', '흐림', '23', '30'],
 ['평택', '2022-07-07 00:00', '흐림', '24', '30'],
 ['평택', '2022-07-08 00:00', '흐림', '23', '32'],
 ['춘천', '2022-07-01 00:00', '흐리고 비', '23', '29'],
 ['춘천', '2022-07-01 12:00', '흐리고 비', '23', '29'],
 ['춘천', '2022-07-02 00:00', '흐림', '23', '30'],
 ['춘천', '2022-07-02 12:00', '흐림', '23', '30'],
 ['춘천', '2022-07-03 00:00', '구름많음', '22', '30'],
 ['춘천', '2022-07-03 12:00', '흐림', '22', '30'],
 ['춘천', '2022-07-04 00:00', '흐림', '23', '29'],
 ['춘천', '2022-07-04 12:00', '흐림', '23', '29'],
 ['춘천', '2022-07-05 00:00', '흐림', '23', '28'],
 ['춘천', '2022-07-05 12:00', '흐리고 비', '23', '28'],
 ['춘천', '2022-07-06 00:00', '흐림', '23', '29'],
 ['춘천', '2022-07-07 00:00', '흐림', '23', '29'],
 ['춘천', '2022-07-08 00:00', '흐림', '23', '29'],
 ['원주', '2022-07-01 00:00', '흐리고 비', '23', '30'],
 ['원주', '2022-07-01 12:00', '흐리고 비', '23', '30'],
 ['원주', '2022-07-02 00:00', '흐림', '23', '30'],
 ['원주', '2022-07-02 12:00', '흐림', '23', '30'],
 ['원주', '2022-07-03 00:00', '구름많음', '22', '30'],
 ['원주', '2022-07-03 12:00', '흐림', '22', '30'],
 ['원주', '2022-07-04 00:00', '흐림', '23', '29'],
 ['원주', '2022-07-04 12:00', '흐림', '23', '29'],
 ['원주', '2022-07-05 00:00', '흐림', '23', '30'],
 ['원주', '2022-07-05 12:00', '흐리고 비', '23', '30'],
 ['원주', '2022-07-06 00:00', '흐림', '23', '30'],
 ['원주', '2022-07-07 00:00', '흐림', '23', '30'],
 ['원주', '2022-07-08 00:00', '흐림', '23', '30'],
 ['강릉', '2022-07-01 00:00', '흐림', '23', '28'],
 ['강릉', '2022-07-01 12:00', '흐림', '23', '28'],
 ['강릉', '2022-07-02 00:00', '구름많음', '24', '29'],
 ['강릉', '2022-07-02 12:00', '구름많음', '24', '29'],
 ['강릉', '2022-07-03 00:00', '구름많음', '24', '30'],
 ['강릉', '2022-07-03 12:00', '구름많음', '24', '30'],
 ['강릉', '2022-07-04 00:00', '흐림', '24', '30'],
 ['강릉', '2022-07-04 12:00', '흐림', '24', '30'],
 ['강릉', '2022-07-05 00:00', '흐림', '23', '29'],
 ['강릉', '2022-07-05 12:00', '흐리고 비', '23', '29'],
 ['강릉', '2022-07-06 00:00', '흐림', '24', '31'],
 ['강릉', '2022-07-07 00:00', '흐림', '24', '30'],
 ['강릉', '2022-07-08 00:00', '흐림', '23', '29'],
 ['대전', '2022-07-01 00:00', '구름많음', '24', '31'],
 ['대전', '2022-07-01 12:00', '흐림', '24', '31'],
 ['대전', '2022-07-02 00:00', '구름많음', '24', '32'],
 ['대전', '2022-07-02 12:00', '구름많음', '24', '32'],
 ['대전', '2022-07-03 00:00', '구름많음', '23', '31'],
 ['대전', '2022-07-03 12:00', '흐림', '23', '31'],
 ['대전', '2022-07-04 00:00', '흐림', '24', '29'],
 ['대전', '2022-07-04 12:00', '흐림', '24', '29'],
 ['대전', '2022-07-05 00:00', '흐림', '24', '30'],
 ['대전', '2022-07-05 12:00', '흐리고 비', '24', '30'],
 ['대전', '2022-07-06 00:00', '흐림', '24', '31'],
 ['대전', '2022-07-07 00:00', '흐림', '24', '30'],
 ['대전', '2022-07-08 00:00', '흐림', '24', '31'],
 ['세종', '2022-07-01 00:00', '구름많음', '23', '30'],
 ['세종', '2022-07-01 12:00', '흐림', '23', '30'],
 ['세종', '2022-07-02 00:00', '구름많음', '23', '31'],
 ['세종', '2022-07-02 12:00', '구름많음', '23', '31'],
 ['세종', '2022-07-03 00:00', '구름많음', '23', '31'],
 ['세종', '2022-07-03 12:00', '흐림', '23', '31'],
 ['세종', '2022-07-04 00:00', '흐림', '23', '29'],
 ['세종', '2022-07-04 12:00', '흐림', '23', '29'],
 ['세종', '2022-07-05 00:00', '흐림', '23', '29'],
 ['세종', '2022-07-05 12:00', '흐리고 비', '23', '29'],
 ['세종', '2022-07-06 00:00', '흐림', '24', '30'],
 ['세종', '2022-07-07 00:00', '흐림', '23', '30'],
 ['세종', '2022-07-08 00:00', '흐림', '23', '31'],
 ['홍성', '2022-07-01 00:00', '구름많음', '23', '30'],
 ['홍성', '2022-07-01 12:00', '흐림', '23', '30'],
 ['홍성', '2022-07-02 00:00', '구름많음', '23', '32'],
 ['홍성', '2022-07-02 12:00', '구름많음', '23', '32'],
 ['홍성', '2022-07-03 00:00', '구름많음', '22', '30'],
 ['홍성', '2022-07-03 12:00', '흐림', '22', '30'],
 ['홍성', '2022-07-04 00:00', '흐림', '23', '28'],
 ['홍성', '2022-07-04 12:00', '흐림', '23', '28'],
 ['홍성', '2022-07-05 00:00', '흐림', '23', '27'],
 ['홍성', '2022-07-05 12:00', '흐리고 비', '23', '27'],
 ['홍성', '2022-07-06 00:00', '흐림', '24', '28'],
 ['홍성', '2022-07-07 00:00', '흐림', '23', '28'],
 ['홍성', '2022-07-08 00:00', '흐림', '23', '30'],
 ['청주', '2022-07-01 00:00', '흐림', '24', '31'],
 ['청주', '2022-07-01 12:00', '흐림', '24', '31'],
 ['청주', '2022-07-02 00:00', '구름많음', '24', '32'],
 ['청주', '2022-07-02 12:00', '구름많음', '24', '32'],
 ['청주', '2022-07-03 00:00', '구름많음', '24', '31'],
 ['청주', '2022-07-03 12:00', '흐림', '24', '31'],
 ['청주', '2022-07-04 00:00', '흐림', '24', '30'],
 ['청주', '2022-07-04 12:00', '흐림', '24', '30'],
 ['청주', '2022-07-05 00:00', '흐림', '24', '31'],
 ['청주', '2022-07-05 12:00', '흐리고 비', '24', '31'],
 ['청주', '2022-07-06 00:00', '흐림', '24', '31'],
 ['청주', '2022-07-07 00:00', '흐림', '24', '31'],
 ['청주', '2022-07-08 00:00', '흐림', '24', '31'],
 ['충주', '2022-07-01 00:00', '흐림', '22', '31'],
 ['충주', '2022-07-01 12:00', '흐림', '22', '31'],
 ['충주', '2022-07-02 00:00', '구름많음', '23', '32'],
 ['충주', '2022-07-02 12:00', '구름많음', '23', '32'],
 ['충주', '2022-07-03 00:00', '구름많음', '22', '30'],
 ['충주', '2022-07-03 12:00', '흐림', '22', '30'],
 ['충주', '2022-07-04 00:00', '흐림', '22', '30'],
 ['충주', '2022-07-04 12:00', '흐림', '22', '30'],
 ['충주', '2022-07-05 00:00', '흐림', '23', '30'],
 ['충주', '2022-07-05 12:00', '흐리고 비', '23', '30'],
 ['충주', '2022-07-06 00:00', '흐림', '23', '30'],
 ['충주', '2022-07-07 00:00', '흐림', '23', '30'],
 ['충주', '2022-07-08 00:00', '흐림', '23', '31'],
 ['영동', '2022-07-01 00:00', '흐림', '21', '32'],
 ['영동', '2022-07-01 12:00', '흐림', '21', '32'],
 ['영동', '2022-07-02 00:00', '구름많음', '22', '33'],
 ['영동', '2022-07-02 12:00', '구름많음', '22', '33'],
 ['영동', '2022-07-03 00:00', '구름많음', '21', '31'],
 ['영동', '2022-07-03 12:00', '흐림', '21', '31'],
 ['영동', '2022-07-04 00:00', '흐림', '22', '29'],
 ['영동', '2022-07-04 12:00', '흐림', '22', '29'],
 ['영동', '2022-07-05 00:00', '흐림', '22', '30'],
 ['영동', '2022-07-05 12:00', '흐리고 비', '22', '30'],
 ['영동', '2022-07-06 00:00', '흐림', '22', '31'],
 ['영동', '2022-07-07 00:00', '흐림', '23', '31'],
 ['영동', '2022-07-08 00:00', '흐림', '22', '32'],
 ['광주', '2022-07-01 00:00', '구름많음', '24', '32'],
 ['광주', '2022-07-01 12:00', '구름많음', '24', '32'],
 ['광주', '2022-07-02 00:00', '구름많음', '24', '32'],
 ['광주', '2022-07-02 12:00', '구름많음', '24', '32'],
 ['광주', '2022-07-03 00:00', '구름많음', '23', '31'],
 ['광주', '2022-07-03 12:00', '흐림', '23', '31'],
 ['광주', '2022-07-04 00:00', '흐림', '24', '30'],
 ['광주', '2022-07-04 12:00', '흐림', '24', '30'],
 ['광주', '2022-07-05 00:00', '흐리고 비', '24', '30'],
 ['광주', '2022-07-05 12:00', '흐림', '24', '30'],
 ['광주', '2022-07-06 00:00', '흐림', '24', '30'],
 ['광주', '2022-07-07 00:00', '흐림', '24', '31'],
 ['광주', '2022-07-08 00:00', '흐림', '24', '31'],
 ['목포', '2022-07-01 00:00', '구름많음', '24', '30'],
 ['목포', '2022-07-01 12:00', '구름많음', '24', '30'],
 ['목포', '2022-07-02 00:00', '구름많음', '23', '30'],
 ['목포', '2022-07-02 12:00', '구름많음', '23', '30'],
 ['목포', '2022-07-03 00:00', '구름많음', '23', '29'],
 ['목포', '2022-07-03 12:00', '흐림', '23', '29'],
 ['목포', '2022-07-04 00:00', '흐림', '23', '27'],
 ['목포', '2022-07-04 12:00', '흐림', '23', '27'],
 ['목포', '2022-07-05 00:00', '흐리고 비', '23', '28'],
 ['목포', '2022-07-05 12:00', '흐림', '23', '28'],
 ['목포', '2022-07-06 00:00', '흐림', '24', '28'],
 ['목포', '2022-07-07 00:00', '흐림', '24', '29'],
 ['목포', '2022-07-08 00:00', '흐림', '23', '29'],
 ['여수', '2022-07-01 00:00', '구름많음', '23', '27'],
 ['여수', '2022-07-01 12:00', '구름많음', '23', '27'],
 ['여수', '2022-07-02 00:00', '구름많음', '23', '28'],
 ['여수', '2022-07-02 12:00', '구름많음', '23', '28'],
 ['여수', '2022-07-03 00:00', '구름많음', '23', '27'],
 ['여수', '2022-07-03 12:00', '흐림', '23', '27'],
 ['여수', '2022-07-04 00:00', '흐림', '23', '26'],
 ['여수', '2022-07-04 12:00', '흐림', '23', '26'],
 ['여수', '2022-07-05 00:00', '흐리고 비', '23', '26'],
 ['여수', '2022-07-05 12:00', '흐림', '23', '26'],
 ['여수', '2022-07-06 00:00', '흐림', '23', '27'],
 ['여수', '2022-07-07 00:00', '흐림', '23', '28'],
 ['여수', '2022-07-08 00:00', '흐림', '23', '28'],
 ['순천', '2022-07-01 00:00', '구름많음', '24', '30'],
 ['순천', '2022-07-01 12:00', '구름많음', '24', '30'],
 ['순천', '2022-07-02 00:00', '구름많음', '24', '31'],
 ['순천', '2022-07-02 12:00', '구름많음', '24', '31'],
 ['순천', '2022-07-03 00:00', '구름많음', '23', '30'],
 ['순천', '2022-07-03 12:00', '흐림', '23', '30'],
 ['순천', '2022-07-04 00:00', '흐림', '24', '27'],
 ['순천', '2022-07-04 12:00', '흐림', '24', '27'],
 ['순천', '2022-07-05 00:00', '흐리고 비', '24', '29'],
 ['순천', '2022-07-05 12:00', '흐림', '24', '29'],
 ['순천', '2022-07-06 00:00', '흐림', '24', '30'],
 ['순천', '2022-07-07 00:00', '흐림', '24', '30'],
 ['순천', '2022-07-08 00:00', '흐림', '24', '30'],
 ['광양', '2022-07-01 00:00', '구름많음', '23', '31'],
 ['광양', '2022-07-01 12:00', '구름많음', '23', '31'],
 ['광양', '2022-07-02 00:00', '구름많음', '23', '31'],
 ['광양', '2022-07-02 12:00', '구름많음', '23', '31'],
 ['광양', '2022-07-03 00:00', '구름많음', '23', '30'],
 ['광양', '2022-07-03 12:00', '흐림', '23', '30'],
 ['광양', '2022-07-04 00:00', '흐림', '23', '28'],
 ['광양', '2022-07-04 12:00', '흐림', '23', '28'],
 ['광양', '2022-07-05 00:00', '흐리고 비', '24', '29'],
 ['광양', '2022-07-05 12:00', '흐림', '24', '29'],
 ['광양', '2022-07-06 00:00', '흐림', '24', '30'],
 ['광양', '2022-07-07 00:00', '흐림', '24', '30'],
 ['광양', '2022-07-08 00:00', '흐림', '25', '30'],
 ['나주', '2022-07-01 00:00', '구름많음', '23', '31'],
 ['나주', '2022-07-01 12:00', '구름많음', '23', '31'],
 ['나주', '2022-07-02 00:00', '구름많음', '23', '32'],
 ['나주', '2022-07-02 12:00', '구름많음', '23', '32'],
 ['나주', '2022-07-03 00:00', '구름많음', '22', '31'],
 ['나주', '2022-07-03 12:00', '흐림', '22', '31'],
 ['나주', '2022-07-04 00:00', '흐림', '23', '28'],
 ['나주', '2022-07-04 12:00', '흐림', '23', '28'],
 ['나주', '2022-07-05 00:00', '흐리고 비', '24', '30'],
 ['나주', '2022-07-05 12:00', '흐림', '24', '30'],
 ['나주', '2022-07-06 00:00', '흐림', '24', '30'],
 ['나주', '2022-07-07 00:00', '흐림', '23', '31'],
 ['나주', '2022-07-08 00:00', '흐림', '24', '31'],
 ['전주', '2022-07-01 00:00', '구름많음', '24', '32'],
 ['전주', '2022-07-01 12:00', '흐림', '24', '32'],
 ['전주', '2022-07-02 00:00', '구름많음', '23', '32'],
 ['전주', '2022-07-02 12:00', '구름많음', '23', '32'],
 ['전주', '2022-07-03 00:00', '구름많음', '23', '31'],
 ['전주', '2022-07-03 12:00', '흐림', '23', '31'],
 ['전주', '2022-07-04 00:00', '흐림', '24', '30'],
 ['전주', '2022-07-04 12:00', '흐림', '24', '30'],
 ['전주', '2022-07-05 00:00', '흐리고 비', '24', '31'],
 ['전주', '2022-07-05 12:00', '흐림', '24', '31'],
 ['전주', '2022-07-06 00:00', '흐림', '24', '31'],
 ['전주', '2022-07-07 00:00', '흐림', '24', '31'],
 ['전주', '2022-07-08 00:00', '흐림', '24', '32'],
 ['군산', '2022-07-01 00:00', '구름많음', '23', '30'],
 ['군산', '2022-07-01 12:00', '흐림', '23', '30'],
 ['군산', '2022-07-02 00:00', '구름많음', '23', '31'],
 ['군산', '2022-07-02 12:00', '구름많음', '23', '31'],
 ['군산', '2022-07-03 00:00', '구름많음', '22', '29'],
 ['군산', '2022-07-03 12:00', '흐림', '22', '29'],
 ['군산', '2022-07-04 00:00', '흐림', '23', '29'],
 ['군산', '2022-07-04 12:00', '흐림', '23', '29'],
 ['군산', '2022-07-05 00:00', '흐리고 비', '23', '29'],
 ['군산', '2022-07-05 12:00', '흐림', '23', '29'],
 ['군산', '2022-07-06 00:00', '흐림', '24', '29'],
 ['군산', '2022-07-07 00:00', '흐림', '24', '30'],
 ['군산', '2022-07-08 00:00', '흐림', '23', '30'],
 ['정읍', '2022-07-01 00:00', '구름많음', '24', '31'],
 ['정읍', '2022-07-01 12:00', '흐림', '24', '31'],
 ['정읍', '2022-07-02 00:00', '구름많음', '23', '32'],
 ['정읍', '2022-07-02 12:00', '구름많음', '23', '32'],
 ['정읍', '2022-07-03 00:00', '구름많음', '22', '31'],
 ['정읍', '2022-07-03 12:00', '흐림', '22', '31'],
 ['정읍', '2022-07-04 00:00', '흐림', '23', '30'],
 ['정읍', '2022-07-04 12:00', '흐림', '23', '30'],
 ['정읍', '2022-07-05 00:00', '흐리고 비', '24', '30'],
 ['정읍', '2022-07-05 12:00', '흐림', '24', '30'],
 ['정읍', '2022-07-06 00:00', '흐림', '24', '31'],
 ['정읍', '2022-07-07 00:00', '흐림', '24', '31'],
 ['정읍', '2022-07-08 00:00', '흐림', '24', '31'],
 ['남원', '2022-07-01 00:00', '구름많음', '22', '32'],
 ['남원', '2022-07-01 12:00', '흐림', '22', '32'],
 ['남원', '2022-07-02 00:00', '구름많음', '22', '32'],
 ['남원', '2022-07-02 12:00', '구름많음', '22', '32'],
 ['남원', '2022-07-03 00:00', '구름많음', '22', '31'],
 ['남원', '2022-07-03 12:00', '흐림', '22', '31'],
 ['남원', '2022-07-04 00:00', '흐림', '23', '29'],
 ['남원', '2022-07-04 12:00', '흐림', '23', '29'],
 ['남원', '2022-07-05 00:00', '흐리고 비', '23', '30'],
 ['남원', '2022-07-05 12:00', '흐림', '23', '30'],
 ['남원', '2022-07-06 00:00', '흐림', '23', '31'],
 ['남원', '2022-07-07 00:00', '흐림', '23', '31'],
 ['남원', '2022-07-08 00:00', '흐림', '23', '32'],
 ['고창', '2022-07-01 00:00', '구름많음', '23', '31'],
 ['고창', '2022-07-01 12:00', '흐림', '23', '31'],
 ['고창', '2022-07-02 00:00', '구름많음', '23', '31'],
 ['고창', '2022-07-02 12:00', '구름많음', '23', '31'],
 ['고창', '2022-07-03 00:00', '구름많음', '22', '30'],
 ['고창', '2022-07-03 12:00', '흐림', '22', '30'],
 ['고창', '2022-07-04 00:00', '흐림', '23', '29'],
 ['고창', '2022-07-04 12:00', '흐림', '23', '29'],
 ['고창', '2022-07-05 00:00', '흐리고 비', '24', '30'],
 ['고창', '2022-07-05 12:00', '흐림', '24', '30'],
 ['고창', '2022-07-06 00:00', '흐림', '24', '30'],
 ['고창', '2022-07-07 00:00', '흐림', '24', '30'],
 ['고창', '2022-07-08 00:00', '흐림', '24', '30'],
 ['무주', '2022-07-01 00:00', '구름많음', '21', '31'],
 ['무주', '2022-07-01 12:00', '흐림', '21', '31'],
 ['무주', '2022-07-02 00:00', '구름많음', '21', '32'],
 ['무주', '2022-07-02 12:00', '구름많음', '21', '32'],
 ['무주', '2022-07-03 00:00', '구름많음', '21', '31'],
 ['무주', '2022-07-03 12:00', '흐림', '21', '31'],
 ['무주', '2022-07-04 00:00', '흐림', '22', '28'],
 ['무주', '2022-07-04 12:00', '흐림', '22', '28'],
 ['무주', '2022-07-05 00:00', '흐리고 비', '22', '29'],
 ['무주', '2022-07-05 12:00', '흐림', '22', '29'],
 ['무주', '2022-07-06 00:00', '흐림', '23', '30'],
 ['무주', '2022-07-07 00:00', '흐림', '23', '30'],
 ['무주', '2022-07-08 00:00', '흐림', '22', '31'],
 ['부산', '2022-07-01 00:00', '구름많음', '23', '28'],
 ['부산', '2022-07-01 12:00', '구름많음', '23', '28'],
 ['부산', '2022-07-02 00:00', '구름많음', '23', '29'],
 ['부산', '2022-07-02 12:00', '구름많음', '23', '29'],
 ['부산', '2022-07-03 00:00', '구름많음', '23', '28'],
 ['부산', '2022-07-03 12:00', '구름많음', '23', '28'],
 ['부산', '2022-07-04 00:00', '흐림', '23', '27'],
 ['부산', '2022-07-04 12:00', '흐림', '23', '27'],
 ['부산', '2022-07-05 00:00', '흐리고 비', '23', '27'],
 ['부산', '2022-07-05 12:00', '흐림', '23', '27'],
 ['부산', '2022-07-06 00:00', '흐림', '23', '28'],
 ['부산', '2022-07-07 00:00', '흐림', '23', '28'],
 ['부산', '2022-07-08 00:00', '흐림', '23', '27'],
 ['울산', '2022-07-01 00:00', '구름많음', '23', '32'],
 ['울산', '2022-07-01 12:00', '구름많음', '23', '32'],
 ['울산', '2022-07-02 00:00', '구름많음', '23', '32'],
 ['울산', '2022-07-02 12:00', '구름많음', '23', '32'],
 ['울산', '2022-07-03 00:00', '구름많음', '23', '31'],
 ['울산', '2022-07-03 12:00', '구름많음', '23', '31'],
 ['울산', '2022-07-04 00:00', '흐림', '23', '29'],
 ['울산', '2022-07-04 12:00', '흐림', '23', '29'],
 ['울산', '2022-07-05 00:00', '흐리고 비', '23', '30'],
 ['울산', '2022-07-05 12:00', '흐림', '23', '30'],
 ['울산', '2022-07-06 00:00', '흐림', '23', '30'],
 ['울산', '2022-07-07 00:00', '흐림', '24', '31'],
 ['울산', '2022-07-08 00:00', '흐림', '23', '31'],
 ['창원', '2022-07-01 00:00', '구름많음', '23', '30'],
 ['창원', '2022-07-01 12:00', '구름많음', '23', '30'],
 ['창원', '2022-07-02 00:00', '구름많음', '22', '30'],
 ['창원', '2022-07-02 12:00', '구름많음', '22', '30'],
 ['창원', '2022-07-03 00:00', '구름많음', '22', '30'],
 ['창원', '2022-07-03 12:00', '구름많음', '22', '30'],
 ['창원', '2022-07-04 00:00', '흐림', '23', '28'],
 ['창원', '2022-07-04 12:00', '흐림', '23', '28'],
 ['창원', '2022-07-05 00:00', '흐리고 비', '23', '29'],
 ['창원', '2022-07-05 12:00', '흐림', '23', '29'],
 ['창원', '2022-07-06 00:00', '흐림', '23', '29'],
 ['창원', '2022-07-07 00:00', '흐림', '23', '30'],
 ['창원', '2022-07-08 00:00', '흐림', '23', '30'],
 ['진주', '2022-07-01 00:00', '구름많음', '23', '30'],
 ['진주', '2022-07-01 12:00', '구름많음', '23', '30'],
 ['진주', '2022-07-02 00:00', '구름많음', '22', '31'],
 ['진주', '2022-07-02 12:00', '구름많음', '22', '31'],
 ['진주', '2022-07-03 00:00', '구름많음', '22', '30'],
 ['진주', '2022-07-03 12:00', '구름많음', '22', '30'],
 ['진주', '2022-07-04 00:00', '흐림', '23', '28'],
 ['진주', '2022-07-04 12:00', '흐림', '23', '28'],
 ['진주', '2022-07-05 00:00', '흐리고 비', '23', '29'],
 ['진주', '2022-07-05 12:00', '흐림', '23', '29'],
 ['진주', '2022-07-06 00:00', '흐림', '23', '30'],
 ['진주', '2022-07-07 00:00', '흐림', '23', '30'],
 ['진주', '2022-07-08 00:00', '흐림', '23', '30'],
 ['거창', '2022-07-01 00:00', '구름많음', '21', '32'],
 ['거창', '2022-07-01 12:00', '구름많음', '21', '32'],
 ['거창', '2022-07-02 00:00', '구름많음', '21', '32'],
 ['거창', '2022-07-02 12:00', '구름많음', '21', '32'],
 ['거창', '2022-07-03 00:00', '구름많음', '21', '30'],
 ['거창', '2022-07-03 12:00', '구름많음', '21', '30'],
 ['거창', '2022-07-04 00:00', '흐림', '22', '28'],
 ['거창', '2022-07-04 12:00', '흐림', '22', '28'],
 ['거창', '2022-07-05 00:00', '흐리고 비', '22', '30'],
 ['거창', '2022-07-05 12:00', '흐림', '22', '30'],
 ['거창', '2022-07-06 00:00', '흐림', '22', '30'],
 ['거창', '2022-07-07 00:00', '흐림', '22', '31'],
 ['거창', '2022-07-08 00:00', '흐림', '22', '31'],

In [44]:
import pandas as pd

In [59]:
weatherDataFrame = pd.DataFrame(tempList, columns=['city','tmef','wf','tmn','tmx'])
weatherDataFrame

    city              tmef     wf tmn tmx
0     서울  2022-07-01 00:00  흐리고 비  23  28
1     서울  2022-07-01 12:00  흐리고 비  23  28
2     서울  2022-07-02 00:00     흐림  23  29
3     서울  2022-07-02 12:00   구름많음  23  29
4     서울  2022-07-03 00:00   구름많음  23  30
..   ...               ...    ...  ..  ..
528  서귀포  2022-07-05 00:00  흐리고 비  24  27
529  서귀포  2022-07-05 12:00     흐림  24  27
530  서귀포  2022-07-06 00:00     흐림  24  28
531  서귀포  2022-07-07 00:00     흐림  24  28
532  서귀포  2022-07-08 00:00     흐림  24  28

[533 rows x 5 columns]

In [60]:
engine = create_engine("mysql+pymysql://root:qwer1234@127.0.0.1:3306/weather")
conn = engine.connect()

In [61]:
weatherDataFrame.to_sql(name="forecast", con=engine, if_exists='append', index=False)

In [62]:
ridiTable = pd.read_sql_table('forecast', conn)
ridiTable.head()

   seq city                tmef     wf  tmn  tmx
0    1   서울 2022-07-01 00:00:00  흐리고 비   23   28
1    2   서울 2022-07-01 12:00:00  흐리고 비   23   28
2    3   서울 2022-07-02 00:00:00     흐림   23   29
3    4   서울 2022-07-02 12:00:00   구름많음   23   29
4    5   서울 2022-07-03 00:00:00   구름많음   23   30