In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By

In [2]:
# Chrome Browser와 Chrome Driver Version 확인하기

chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),options=chrome_options)
driver.get('https://news.daum.net/')

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 103.0.5060
[WDM] - Get LATEST chromedriver version for 103.0.5060 google-chrome
[WDM] - About to download new driver from https://chromedriver.storage.googleapis.com/103.0.5060.53/chromedriver_mac64.zip
[WDM] - Driver has been saved in cache [/Users/tj/.wdm/drivers/chromedriver/mac64/103.0.5060.53]

In [3]:
from bs4 import BeautifulSoup

In [4]:
page_source = driver.page_source
soup = BeautifulSoup(page_source,'html.parser')

In [28]:
newsTitle_name = []


news_title = soup.select("div.box_g.box_news_issue strong a")
for i in range(len(news_title)):
    newsTitle_name.append(news_title[i].string.strip())

In [45]:
newsCompany = []

news_name = soup.select("div.box_g.box_news_issue .link_txt")
for i in range(len(news_name)):
    newsCompany.append(news_name[i]['href'])

In [47]:
len(newsCompany)

20

In [43]:
len(newsTitle_name)

20

In [49]:
import pandas as pd

In [53]:
daumNews = pd.DataFrame(data=newsCompany, columns=['뉴스회사'] )
daumNews

                                      뉴스회사
0   https://v.daum.net/v/20220708142549025
1   https://v.daum.net/v/20220708141828799
2   https://v.daum.net/v/20220708142117887
3   https://v.daum.net/v/20220708142101875
4   https://v.daum.net/v/20220708141510693
5   https://v.daum.net/v/20220708140950570
6   https://v.daum.net/v/20220708141700745
7   https://v.daum.net/v/20220708141612725
8   https://v.daum.net/v/20220708141611722
9   https://v.daum.net/v/20220708140536453
10  https://v.daum.net/v/20220708140008276
11  https://v.daum.net/v/20220708141324655
12  https://v.daum.net/v/20220708135722205
13  https://v.daum.net/v/20220708141024586
14  https://v.daum.net/v/20220708140948569
15  https://v.daum.net/v/20220708140016291
16  https://v.daum.net/v/20220708135922251
17  https://v.daum.net/v/20220708140624483
18  https://v.daum.net/v/20220708135713199
19  https://v.daum.net/v/20220708140423417

In [54]:
daumNews['뉴스제목'] = pd.Series(newsTitle_name)
daumNews

,뉴스회사,뉴스제목
0,https://v.daum.net/v/20220708142549025,"中 매체들, 아베 피격 신속 보도"
1,https://v.daum.net/v/20220708141828799,다시 들썩이는 원전주들..이유는
2,https://v.daum.net/v/20220708142117887,귀 가려울 때 '여기' 누르면 해소
3,https://v.daum.net/v/20220708142101875,"재감염률 높은 BA.5 국내서도 급증..정부, 13일 대책 발표"
4,https://v.daum.net/v/20220708141510693,"아베 저격 현장 목격자..""뒤에서 바주카포같은 총으로 쏴"""
5,https://v.daum.net/v/20220708140950570,"외교부, 日 아베 전 총리 피격 사건에 ""아직 언급 자제"""
6,https://v.daum.net/v/20220708141700745,교보생명 IPO 초읽기..주주 갈등 분수령 '주목'
7,https://v.daum.net/v/20220708141612725,"민주당 ""공관위 구성, 최고위는 '심의'만""..이재명계 '안도'"
8,https://v.daum.net/v/20220708141611722,"MB 처남댁, '다스 증여세 불복' 2심도 승소..9억→600만원"
9,https://v.daum.net/v/20220708140536453,"윤건영 충북교육감 ""생각의 힘 키우려면 효과적 독서교육 중요"""
10,https://v.daum.net/v/20220708140008276,"""미국 기준금리 3.75%까지 오르면 한국 GDP 0.7%↓·환율 16%↑"""
11,https://v.daum.net/v/20220708141324655,아베 신조 전 총리 피습..일본 현지 반응은?[더뉴스]
12,https://v.daum.net/v/20220708135722205,"국립횡성숲체원, 산촌체험 여행상품 '같이 살림' 8월부터 운영"
13,https://v.daum.net/v/20220708141024586,돼지·소·닭이 1번 대책인 이유..새 물가대책 의미와 한계
14,https://v.daum.net/v/20220708140948569,"지방선거앞..마약 걸린 행정관, 알고도 사표 받아준 文청와대"
15,https://v.daum.net/v/20220708140016291,장맛비 없이 곳곳 무더위·열대야..강원 한때 소나기[주말날씨]
16,https://v.daum.net/v/20220708135922251,외인 매수세에 코스피 0.94% 상승..코스닥은 1%↑[장중시황]
17,https://v.daum.net/v/20220708140624483,"印기상청, 폭우로 일상 마비된 뭄바이에 적생경보 발령"
18,https://v.daum.net/v/20220708135713199,서울 아파트값 강남·동작만 상승..하락지역 14개로 늘어
19,https://v.daum.net/v/20220708140423417,러시아판 맥도날드라더니.. '곰팡이 버거'에 시끌

In [55]:
from sqlalchemy import create_engine

In [56]:
engine = create_engine("mysql+pymysql://root:qwer1234@127.0.0.1:3306/weather")
conn = engine.connect()

In [57]:
daumNews.to_sql(name="daumNews", con=engine, if_exists='append', index=False)